# -*- coding: utf-8 -*-
"""G2_notebook2_analise-temporal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cAkohsky3BwrRqQXbztf2RqtStkUGsVH

# **Análise temporal de uso e cobertura da zona costeira via imagens Sentinel-2 com classificação não supervisionada e índices espectrais**

Este pipeline implementa uma análise geoespacial completa e multitemporal da evolução costeira entre 2019 e 2025 utilizando imagens Sentinel-2 do Google Earth Engine. Inicialmente, as cenas são filtradas por região de interesse, período temporal e cobertura de nuvens, seguidas pela aplicação de mascaramento atmosférico e composição das imagens mais representativas por mediana. Em seguida, são derivados índices espectrais (NDVI, MNDWI, NDBI e BSI) para realçar diferentes componentes ambientais, como vegetação, água, áreas urbanizadas e solo exposto.

Os dados multiespectrais são organizados em um stack integrado, convertidos para formato NumPy e submetidos a etapas rigorosas de limpeza, normalização e padronização. A partir disso, aplica-se o algoritmo de clustering KMeans para segmentação não supervisionada da paisagem, permitindo a identificação de padrões espectrais sem amostras prévias. Os clusters são posteriormente interpretados e reclassificados em classes temáticas (água, areia, vegetação e urbanização).

O fluxo inclui ainda estimativas de área por classe, geração de mapas temáticos, visualização dos clusters individuais e análise de consistência espacial. Por fim, realiza-se uma análise comparativa temporal entre os dois anos por meio de matrizes de confusão, métricas de acurácia, mapas de mudança e quantificação das variações de área, permitindo identificar e quantificar processos de transformação da cobertura e uso do solo ao longo do período estudado.

# **Importação de bibliotecas e inicialização do ambiente**

Importa as bibliotecas necessárias para processamento de imagens, classificação, visualização e avaliação dos resultados, além de autenticar e inicializar o Google Earth Engine para acesso aos dados geoespaciais.
"""

import ee
import geemap
import numpy as np
import matplotlib.pyplot as plt
import cv2
import matplotlib.patches as mpatches

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.mixture import GaussianMixture
from matplotlib.colors import ListedColormap
from matplotlib.patches import Patch
from sklearn.metrics import confusion_matrix
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt

ee.Authenticate()
ee.Initialize(project='trabalho-visao-grupo2')

"""# **Definição da região de interesse (ROI)**

Define a área de estudo por meio de um retângulo geográfico, delimitando a região utilizada para obtenção e processamento das imagens de satélite.
"""

region = ee.Geometry.Rectangle([
   -48.646883,   # esquerda/baixo longitude
   -27.006631,   # esquerda/baixo latitude
   -48.595134,   # direita/cima longitude
   -26.968492    # direita/cima latitude
])

"""# **Função de mascaramento de nuvens**

Define uma função para identificar e remover pixels contaminados por nuvens e cirrus utilizando a banda QA60 das imagens Sentinel-2, além de normalizar os valores de refletância.
"""

def mask_s2_clouds(image):
    qa = image.select('QA60')
    cloud_bit_mask  = 1 << 10
    cirrus_bit_mask = 1 << 11
    mask = (
        qa.bitwiseAnd(cloud_bit_mask).eq(0)
        .And(
            qa.bitwiseAnd(cirrus_bit_mask).eq(0)
        )
    )
    return (
        image
        .updateMask(mask)
        .divide(10000)
    )

"""# **[ANO 1] Seleção das imagens Sentinel-2**

Filtra as imagens Sentinel-2 da região de estudo para o ano de 2019, aplicando critérios de cobertura de nuvens e mascaramento, além de contabilizar as cenas disponíveis para análise.
"""

dataset_2019 = (
    ee.ImageCollection('COPERNICUS/S2_SR_HARMONIZED')
    .filterBounds(region)
    .filterDate(
        '2019-01-01',
        '2019-12-31'
    )
    .filter(
        ee.Filter.lt(
            'CLOUDY_PIXEL_PERCENTAGE',
            15
        )
    )
    .map(mask_s2_clouds)
)

# QUANTIDADE DE IMAGENS

n_images_2019 = dataset_2019.size().getInfo()
print(f'Total de imagens 2019: {n_images_2019}')
image_list_2019 = dataset_2019.toList(
    n_images_2019
)

"""# **[ANO 1] Visualização das imagens**

Exibe todas as imagens Sentinel-2 selecionadas em composição RGB sobre a região de interesse, permitindo a inspeção visual das cenas disponíveis para análise.

"""

# VISUALIZAÇÃO DAS IMAGENS - 2019

Map = geemap.Map()
Map.centerObject(region, 12)

# VISUALIZAÇÃO RGB

vis = {
    'bands': ['B4', 'B3', 'B2'],
    'min': 0.02,
    'max': 0.20,
    'gamma': 1.2
}

# ADICIONAR IMAGENS AO MAPA

for i in range(n_images_2019):
    image = ee.Image(
        image_list_2019.get(i)
    )
    image_id = image.get(
        'system:id'
    ).getInfo()
    print(i, image_id)
    Map.addLayer(
        image,
        vis,
        f'Imagem_2019_{i}',
        False
    )

# ROI

Map.addLayer(
    region,
    {'color': 'red'},
    'ROI'
)

Map

"""# **[ANO 1] Geração da imagem composta**

Seleciona as cenas de interesse, cria uma composição por mediana para reduzir ruídos e variações entre imagens, converte o resultado para formato NumPy, normaliza os valores de refletância e exibe a imagem RGB final.
"""

# ESCOLHA DAS IMAGENS - 2019

selected_indexes_2019 = [6,7]
selected_images_2019 = []

print('\nIMAGENS ESCOLHIDAS - 2019:\n')

for idx in selected_indexes_2019:
    img = ee.Image(
        image_list_2019.get(idx)
    )
    image_id = img.id().getInfo()
    print(f'{idx} -> {image_id}')
    selected_images_2019.append(img)

# COLEÇÃO FINAL

selected_collection_2019 = ee.ImageCollection(
    selected_images_2019
)

# COMPOSIÇÃO FINAL (MEDIANA)

image_ee_2019 = (
    selected_collection_2019
    .median()
)

# RGB PARA NUMPY

image_rgb_2019 = geemap.ee_to_numpy(
    image_ee_2019.select(
        ['B4', 'B3', 'B2']
    ),
    region=region,
    scale=10
)

# VERIFICAÇÃO

if image_rgb_2019 is None:
    raise ValueError(
        "Earth Engine retornou imagem vazia"
    )

# REMOVER NaN

image_rgb_2019 = np.nan_to_num(
    image_rgb_2019
)

# NORMALIZAÇÃO

image_plot_2019 = image_rgb_2019.astype(
    np.float32
)
p2, p98 = np.percentile(
    image_plot_2019,
    (2, 98)
)
image_plot_2019 = np.clip(
    (image_plot_2019 - p2) /
    (p98 - p2 + 1e-8),
    0,
    1
)

# PLOT

plt.figure(figsize=(10,10))
plt.imshow(image_plot_2019)
plt.title(
    'Imagem Final - 2019'
)
plt.axis('off')
plt.tight_layout()
plt.show()

"""# **[ANO 1] Cálculo dos índices espectrais e preparação dos dados**

Calcula os índices espectrais NDVI, MNDWI, NDBI e BSI, gera uma máscara de água, cria um conjunto de dados multiespectral com bandas e índices, remove pixels inválidos e converte os resultados para o formato NumPy para as etapas de classificação.
"""

# NDVI
ndvi_2019 = (
    image_ee_2019.normalizedDifference(
        ['B8', 'B4']
    )
    .rename('NDVI')
)

# MNDWI
mndwi_2019 = (
    image_ee_2019.normalizedDifference(
        ['B3', 'B11']
    )
    .rename('MNDWI')
)

# NDBI
ndbi_2019 = (
    image_ee_2019.normalizedDifference(
        ['B11', 'B8']
    )
    .rename('NDBI')
)

# BSI
bsi_2019 = (
    image_ee_2019.expression(
        '((SWIR + RED) - (NIR + BLUE)) / ((SWIR + RED) + (NIR + BLUE))',
        {
            'SWIR': image_ee_2019.select('B11'),
            'RED' : image_ee_2019.select('B4'),
            'NIR' : image_ee_2019.select('B8'),
            'BLUE': image_ee_2019.select('B2')
        }
    )
    .rename('BSI')
)

# MÁSCARA DE ÁGUA
water_mask_2019 = (
    (mndwi_2019.gt(0.05))
    .And(
        ndvi_2019.lt(0.1)
    )
)

# STACK MULTIESPECTRAL
image_stack_2019 = (
    image_ee_2019.select([
        'B2',
        'B3',
        'B4',
        'B8',
        'B11'
    ])
    .addBands([
        ndvi_2019.multiply(2),
        mndwi_2019.multiply(3),
        ndbi_2019.multiply(2),
        bsi_2019.multiply(2)
    ])
)

# CLIP ROI
image_stack_2019 = image_stack_2019.clip(
    region
)

# REMOVER PIXELS INVÁLIDOS
image_stack_2019 = image_stack_2019.updateMask(

    image_stack_2019.mask().reduce(
        ee.Reducer.min()
    )

)

# CONVERTER PARA NUMPY
image_2019 = geemap.ee_to_numpy(
    image_stack_2019,
    region=region,
    scale=10
)

water_np_2019 = geemap.ee_to_numpy(
    water_mask_2019,
    region=region,
    scale=10
)

water_np_2019 = water_np_2019.astype(bool)

"""# **[ANO 1] Validação, normalização e preparação dos dados para clustering**

Realiza verificações de consistência da imagem, aplica normalização por banda com percentis, suavização espacial, e prepara os pixels válidos (excluindo água e valores nulos) com padronização para uso em algoritmos de classificação não supervisionada.
"""

# VERIFICAÇÃO E NORMALIZAÇÃO - 2019

# VERIFICAÇÃO INICIAL

if image_2019 is None:
    raise ValueError(
        "Earth Engine retornou imagem vazia"
    )

print('\nINFORMAÇÕES DA IMAGEM - 2019:\n')
print(f'Shape: {image_2019.shape}')
print(f'Mínimo: {np.nanmin(image_2019)}')
print(f'Máximo: {np.nanmax(image_2019)}')
print(
    f'Pixels não nulos: {np.count_nonzero(image_2019)}'
)

# IMAGEM VAZIA

if np.count_nonzero(image_2019) == 0:
    raise ValueError(
        "Imagem completamente vazia"
    )

# SEM VARIAÇÃO

if np.nanmax(image_2019) == np.nanmin(image_2019):
    raise ValueError(
        "Imagem sem variação espectral"
    )

# NORMALIZAÇÃO

image_2019 = image_2019.astype(
    np.float32
)

# NORMALIZAÇÃO POR BANDA

for b in range(image_2019.shape[2]):
    band = image_2019[:, :, b]
    p2 = np.nanpercentile(
        band,
        2
    )
    p98 = np.nanpercentile(
        band,
        98
    )
    den = p98 - p2
    if den > 1e-8:
        band = np.clip(
            (band - p2) / den,
            0,
            1
        )
    else:
        print(
            f'Banda {b} constante ou sem variação'
        )
        band = np.zeros_like(band)
    image_2019[:, :, b] = band

# SUAVIZAÇÃO

image_blur_2019 = cv2.GaussianBlur(
    image_2019,
    (5,5),
    0
)

# RGB PARA VISUALIZAÇÃO

rgb_vis_2019 = image_blur_2019[:, :, :3]
rgb_vis_2019 = np.clip(
    rgb_vis_2019,
    0,
    1
)

rgb_vis_2019 = rgb_vis_2019 ** 0.8
rgb_vis_2019 = (
    rgb_vis_2019 * 255
).astype(np.uint8)

# PREPARAÇÃO KMEANS

pixels_2019 = image_blur_2019.reshape(
    (-1, image_blur_2019.shape[2])
)

print('\nFORMATO DOS PIXELS:')
print(pixels_2019.shape)

# REMOVER ÁGUA

water_flat_2019 = water_np_2019.flatten()
pixel_sum_2019 = np.sum(
    np.abs(pixels_2019),
    axis=1
)

valid_pixels_2019 = (
    (pixel_sum_2019 > 0)
    &
    (~water_flat_2019)
)

pixels_valid_2019 = pixels_2019[
    valid_pixels_2019
]

print('\nPIXELS VÁLIDOS:')
print(pixels_valid_2019.shape)

if pixels_valid_2019.shape[0] == 0:
    raise ValueError(
        'Nenhum pixel válido encontrado'
    )

# PADRONIZAÇÃO

scaler_2019 = StandardScaler()
pixels_scaled_2019 = scaler_2019.fit_transform(
    pixels_valid_2019
)

"""# **[ANO 1] Classificação não supervisionada com KMeans**

Aplica o algoritmo KMeans para segmentação da imagem em classes terrestres, reconstrói o mapa de classes incluindo água, recupera os centros espectrais, gera uma visualização RGB colorida dos clusters e exibe comparações entre a imagem original, a segmentação e o mapa de classes resultante.
"""

# KMEANS - 2019

kmeans_2019 = KMeans(
    n_clusters=5, # CLUSTERS TERRESTRES
    random_state=100,
    n_init=100
)

# AJUSTE DO MODELO

kmeans_2019.fit(
    pixels_scaled_2019
)
labels_valid_2019 = (
    kmeans_2019.labels_
)

# RECONSTRUIR MAPA

labels_full_2019 = np.full(
    pixels_2019.shape[0],
    -1
)

# ÁGUA = CLASSE 0

labels_full_2019[
    water_flat_2019
] = 0

# CLUSTERS TERRESTRES

labels_full_2019[
    valid_pixels_2019
] = labels_valid_2019 + 1

# MAPA FINAL

class_map_2019 = labels_full_2019.reshape(
    image_blur_2019.shape[:2]
)

# CENTROS ESPECTRAIS

centers_2019 = (
    kmeans_2019.cluster_centers_
)

# VOLTAR PARA ESCALA ORIGINAL

centers_original_2019 = (
    scaler_2019.inverse_transform(
        centers_2019
    )
)

# RGB DOS CLUSTERS

centers_rgb_2019 = (
    centers_original_2019[:, :3]
)

centers_rgb_2019 = np.clip(
    centers_rgb_2019 * 255,
    0,
    255
).astype(np.uint8)

# IMAGEM SEGMENTADA

segmented_2019 = np.zeros_like(
    rgb_vis_2019
)

# ÁGUA = AZUL

segmented_2019.reshape(
    (-1,3)
)[water_flat_2019] = [0,0,255]

# CORES DOS CLUSTERS

segmented_pixels_2019 = centers_rgb_2019[
    labels_valid_2019
]

segmented_2019.reshape(
    (-1,3)
)[valid_pixels_2019] = segmented_pixels_2019

# PLOT

fig, ax = plt.subplots(
    1,
    3,
    figsize=(20,8)

)

# RGB

ax[0].imshow(
    rgb_vis_2019
)
ax[0].set_title('RGB - 2019')
ax[0].axis('off')

# KMEANS

ax[1].imshow(
    segmented_2019
)
ax[1].set_title('KMeans - 2019')
ax[1].axis('off')

# MAPA DE CLASSES

ax[2].imshow(
    class_map_2019,
    cmap='terrain'
)
ax[2].set_title(
    'Mapa KMeans - 2019'
)
ax[2].axis('off')
plt.tight_layout()
plt.show()

"""# **[ANO 1] Visualização individual dos clusters KMeans**

Gera uma visualização em subplots destacando cada cluster separadamente, aplicando máscara de transparência para enfatizar sua distribuição espacial sobre a imagem RGB original, incluindo a classe de água e os cinco clusters terrestres.
"""

# VISUALIZAÇÃO DOS CLUSTERS - 2019

n_clusters = 5

# SUBPLOTS

fig, ax = plt.subplots(
    2,
    3,
    figsize=(18,10)
)
ax = ax.ravel()

# LOOP DOS CLUSTERS

for i in range(n_clusters + 1):

# MÁSCARA DO CLUSTER

    cluster_mask = (
        class_map_2019 == i
    )

# OVERLAY RGBA

    overlay = np.zeros(
        (
            class_map_2019.shape[0],
            class_map_2019.shape[1],
            4
        ),
        dtype=np.float32
    )

# ESCURECER FORA DO CLUSTER

    overlay[..., 3] = (
        ~cluster_mask
    ) * 0.85

# RGB
    ax[i].imshow(
        rgb_vis_2019
    )

# OVERLAY

    ax[i].imshow(
        overlay
    )

# TÍTULO

    if i == 0:
        title = 'Água'
    else:
        title = f'Cluster {i}'
    ax[i].set_title(title)
    ax[i].axis('off')

# REMOVER EIXOS SOBRANDO

for j in range(
    n_clusters + 1,
    len(ax)
):
    ax[j].axis('off')

# PLOT

plt.tight_layout()
plt.show()

"""# **[ANO 1] Reclassificação temática e estimativa de áreas**

Agrupa os clusters do KMeans em classes temáticas (água, areia, vegetação e urbanização), calcula a área ocupada por cada classe com base no tamanho do pixel, define uma paleta de cores e gera o mapa temático final com legenda quantitativa.
"""

# DEFINIÇÃO DAS CLASSES TEMÁTICAS - 2019

agua_2019 = [0]
areia_2019 = [5]
vegetacao_2019 = [2]
urbanizacao_2019 = [1,3,4]

# MAPA TEMÁTICO

thematic_map_2019 = np.zeros_like(
    class_map_2019
)

# ÁGUA = 0

for c in agua_2019:
    thematic_map_2019[
        class_map_2019 == c
    ] = 0

# AREIA = 1

for c in areia_2019:
    thematic_map_2019[
        class_map_2019 == c
    ] = 1

# VEGETAÇÃO = 2

for c in vegetacao_2019:
    thematic_map_2019[
        class_map_2019 == c
    ] = 2

# URBANIZAÇÃO = 3

for c in urbanizacao_2019:
    thematic_map_2019[
        class_map_2019 == c
    ] = 3

# CÁLCULO DE ÁREA

pixel_area = 100 # m²

area_agua_2019 = np.sum(
    thematic_map_2019 == 0
) * pixel_area

area_areia_2019 = np.sum(
    thematic_map_2019 == 1
) * pixel_area

area_vegetacao_2019 = np.sum(
    thematic_map_2019 == 2
) * pixel_area

area_urbanizacao_2019 = np.sum(
    thematic_map_2019 == 3
) * pixel_area

# CORES

colors = [
    'blue',     # água
    'khaki',    # areia
    'green',    # vegetação
    'gray'      # urbanização
]

cmap = ListedColormap(colors)

# PLOT

plt.figure(figsize=(10,10))
plt.imshow(
    thematic_map_2019,
    cmap=cmap,
    vmin=0,
    vmax=3
)

plt.title(
    'Mapa Temático - 2019'
)

plt.axis('off')

# LEGENDA

legend_elements = [
    Patch(
        facecolor='blue',
        label=f'Água ({area_agua_2019:,.0f} m²)'
    ),

    Patch(
        facecolor='khaki',
        label=f'Areia ({area_areia_2019:,.0f} m²)'
    ),

    Patch(
        facecolor='green',
        label=f'Vegetação ({area_vegetacao_2019:,.0f} m²)'
    ),

    Patch(
        facecolor='gray',
        label=f'Urbanização ({area_urbanizacao_2019:,.0f} m²)'
    )

]

plt.legend(
    handles=legend_elements,
    loc='upper right',
    fontsize=10,
    frameon=True
)

plt.tight_layout()
plt.show()

"""# **[ANO 2] Seleção de imagens Sentinel-2**

Legenda: Filtra as imagens Sentinel-2 da região de interesse com baixa cobertura de nuvens e aplica a máscara de nuvens, organizando as cenas disponíveis em uma lista para processamento posterior.
"""

dataset_2025 = (
    ee.ImageCollection('COPERNICUS/S2_SR_HARMONIZED')
    .filterBounds(region)
    .filterDate(
        '2025-01-01',
        '2025-12-31'
    )
    .filter(
        ee.Filter.lt(
            'CLOUDY_PIXEL_PERCENTAGE',
            15
        )
    )
    .map(mask_s2_clouds)
)

# QUANTIDADE DE IMAGENS
n_images_2025 = dataset_2025.size().getInfo()
print(f'Total de imagens 2025: {n_images_2025}')
image_list_2025 = dataset_2025.toList(
    n_images_2025
)

"""# **[ANO 2] Visualização das imagens Sentinel-2**

Exibe interativamente as cenas Sentinel-2 disponíveis para o ano de 2025 na região de interesse em composição RGB, permitindo inspeção visual das imagens antes da seleção para análise.
"""

# VISUALIZAÇÃO DAS IMAGENS - 2025

Map = geemap.Map()
Map.centerObject(region, 12)

# VISUALIZAÇÃO RGB

vis = {
    'bands': ['B4', 'B3', 'B2'],
    'min': 0.02,
    'max': 0.20,
    'gamma': 1.2
}

# ADICIONAR IMAGENS AO MAPA

for i in range(n_images_2025):
    image = ee.Image(
        image_list_2025.get(i)
    )

    image_id = image.get(
        'system:id'
    ).getInfo()

    print(i, image_id)

    Map.addLayer(
        image,
        vis,
        f'Imagem_2025_{i}',
        False
    )

# ROI

Map.addLayer(
    region,
    {'color': 'red'},
    'ROI'
)

Map

"""# **[ANO 2] Seleção e composição da imagem de 2025**

Seleciona as cenas Sentinel-2 mais adequadas, gera uma composição por mediana, converte para NumPy, trata valores nulos e normaliza a imagem para visualização RGB final da área de estudo.
"""

# ESCOLHA DAS IMAGENS - 2025

selected_indexes_2025 = [3,4,8,9,10]
selected_images_2025 = []

print('\nIMAGENS ESCOLHIDAS - 2025:\n')

for idx in selected_indexes_2025:
    img = ee.Image(
        image_list_2025.get(idx)
    )
    image_id = img.id().getInfo()

    print(f'{idx} -> {image_id}')

    selected_images_2025.append(img)

# COLEÇÃO FINAL

selected_collection_2025 = ee.ImageCollection(
    selected_images_2025
)

# COMPOSIÇÃO FINAL (MEDIANA)

image_ee_2025 = (
    selected_collection_2025
    .median()
)

# RGB PARA NUMPY

image_rgb_2025 = geemap.ee_to_numpy(
    image_ee_2025.select(
        ['B4', 'B3', 'B2']
    ),
    region=region,
    scale=10
)

# VERIFICAÇÃO

if image_rgb_2025 is None:
    raise ValueError(
        "Earth Engine retornou imagem vazia"
    )

# REMOVER NaN

image_rgb_2025 = np.nan_to_num(
    image_rgb_2025
)

# NORMALIZAÇÃO

image_plot_2025 = image_rgb_2025.astype(
    np.float32
)

p2, p98 = np.percentile(
    image_plot_2025,
    (2, 98)
)

image_plot_2025 = np.clip(
    (image_plot_2025 - p2) /
    (p98 - p2 + 1e-8),
    0,
    1
)

# PLOT

plt.figure(figsize=(10,10))
plt.imshow(image_plot_2025)
plt.title(
    'Imagem Final - 2025'
)

plt.axis('off')
plt.tight_layout()
plt.show()

"""# **[ANO 2] Cálculo de índices espectrais e preparação do stack multiespectral**

Legenda: Calcula NDVI, MNDWI, NDBI e BSI a partir da imagem Sentinel-2, gera uma máscara de água, constrói um stack multiespectral com bandas e índices, aplica recorte e limpeza de pixels inválidos e converte os dados para NumPy para análise e classificação.
"""

# ÍNDICES ESPECTRAIS - 2025

# NDVI

ndvi_2025 = (
    image_ee_2025.normalizedDifference(
        ['B8', 'B4']
    )
    .rename('NDVI')
)

# MNDWI

mndwi_2025 = (
    image_ee_2025.normalizedDifference(
        ['B3', 'B11']
    )
    .rename('MNDWI')
)

# NDBI

ndbi_2025 = (
    image_ee_2025.normalizedDifference(
        ['B11', 'B8']
    )
    .rename('NDBI')
)

# BSI

bsi_2025 = (
    image_ee_2025.expression(
        '((SWIR + RED) - (NIR + BLUE)) / ((SWIR + RED) + (NIR + BLUE))',
        {
            'SWIR': image_ee_2025.select('B11'),
            'RED' : image_ee_2025.select('B4'),
            'NIR' : image_ee_2025.select('B8'),
            'BLUE': image_ee_2025.select('B2')
        }
    )
    .rename('BSI')
)

# MÁSCARA DE ÁGUA

water_mask_2025 = (
    (mndwi_2025.gt(0.05))
    .And(
        ndvi_2025.lt(0.1)
    )
)

# STACK MULTIESPECTRAL

image_stack_2025 = (
    image_ee_2025.select([
        'B2',
        'B3',
        'B4',
        'B8',
        'B11'
    ])
    .addBands([
        ndvi_2025.multiply(2),
        mndwi_2025.multiply(3),
        ndbi_2025.multiply(2),
        bsi_2025.multiply(2)
    ])
)

# CLIP ROI

image_stack_2025 = image_stack_2025.clip(
    region
)

# REMOVER PIXELS INVÁLIDOS

image_stack_2025 = image_stack_2025.updateMask(
    image_stack_2025.mask().reduce(
        ee.Reducer.min()
    )
)

# CONVERTER PARA NUMPY

image_2025 = geemap.ee_to_numpy(
    image_stack_2025,
    region=region,
    scale=10
)

water_np_2025 = geemap.ee_to_numpy(
    water_mask_2025,
    region=region,
    scale=10
)

water_np_2025 = water_np_2025.astype(bool)

"""# **[ANO 2] Validação, normalização e preparação dos dados**

Legenda: Realiza verificações de integridade da imagem, aplica normalização por banda com percentis, suavização espacial, separação de pixels válidos (excluindo água e valores nulos) e padronização dos dados para uso em algoritmos de clustering.
"""

# VERIFICAÇÃO E NORMALIZAÇÃO - 2025

# VERIFICAÇÃO INICIAL

if image_2025 is None:
    raise ValueError(
        "Earth Engine retornou imagem vazia"
    )
print('\nINFORMAÇÕES DA IMAGEM - 2025:\n')
print(f'Shape: {image_2025.shape}')
print(f'Mínimo: {np.nanmin(image_2025)}')
print(f'Máximo: {np.nanmax(image_2025)}')
print(
    f'Pixels não nulos: {np.count_nonzero(image_2025)}'
)

# IMAGEM VAZIA

if np.count_nonzero(image_2025) == 0:
    raise ValueError(
        "Imagem completamente vazia"
    )

# SEM VARIAÇÃO

if np.nanmax(image_2025) == np.nanmin(image_2025):
    raise ValueError(
        "Imagem sem variação espectral"
    )

# NORMALIZAÇÃO

image_2025 = image_2025.astype(
    np.float32
)

# NORMALIZAÇÃO POR BANDA

for b in range(image_2025.shape[2]):
    band = image_2025[:, :, b]
    p2 = np.nanpercentile(
        band,
        2
    )
    p98 = np.nanpercentile(
        band,
        98
    )
    den = p98 - p2
    if den > 1e-8:
        band = np.clip(
            (band - p2) / den,
            0,
            1
        )
    else:
        print(
            f'Banda {b} constante ou sem variação'
        )
        band = np.zeros_like(band)
    image_2025[:, :, b] = band

# SUAVIZAÇÃO

image_blur_2025 = cv2.GaussianBlur(
    image_2025,
    (5,5),
    0
)

# RGB PARA VISUALIZAÇÃO

rgb_vis_2025 = image_blur_2025[:, :, :3]
rgb_vis_2025 = np.clip(
    rgb_vis_2025,
    0,
    1
)
rgb_vis_2025 = rgb_vis_2025 ** 0.8
rgb_vis_2025 = (
    rgb_vis_2025 * 255
).astype(np.uint8)

# PREPARAÇÃO KMEANS

pixels_2025 = image_blur_2025.reshape(
    (-1, image_blur_2025.shape[2])
)
print('\nFORMATO DOS PIXELS:')
print(pixels_2025.shape)

# REMOVER ÁGUA

water_flat_2025 = water_np_2025.flatten()
pixel_sum_2025 = np.sum(
    np.abs(pixels_2025),
    axis=1
)

valid_pixels_2025 = (
    (pixel_sum_2025 > 0)
    &
    (~water_flat_2025)
)

pixels_valid_2025 = pixels_2025[
    valid_pixels_2025
]

print('\nPIXELS VÁLIDOS:')
print(pixels_valid_2025.shape)

if pixels_valid_2025.shape[0] == 0:
    raise ValueError(
        'Nenhum pixel válido encontrado'
    )

# PADRONIZAÇÃO

scaler_2025 = StandardScaler()

pixels_scaled_2025 = scaler_2025.fit_transform(
    pixels_valid_2025
)

"""# **[ANO 2] Classificação não supervisionada com KMeans**

Legenda: Aplica o KMeans para segmentação da imagem de 2025, reconstrói o mapa de classes incluindo água, recupera os centros espectrais, gera a visualização RGB colorida dos clusters e compara a imagem original, a segmentação e o mapa de classes resultante.
"""

# KMEANS - 2025

kmeans_2025 = KMeans(
    n_clusters=5, # CLUSTERS TERRESTRES
    random_state=100,
    n_init=100
)

# AJUSTE DO MODELO

kmeans_2025.fit(
    pixels_scaled_2025
)
labels_valid_2025 = (
    kmeans_2025.labels_
)

# RECONSTRUIR MAPA

labels_full_2025 = np.full(
    pixels_2025.shape[0],
    -1
)

# ÁGUA = CLASSE 0

labels_full_2025[
    water_flat_2025
] = 0

# CLUSTERS TERRESTRES

labels_full_2025[
    valid_pixels_2025
] = labels_valid_2025 + 1

# MAPA FINAL

class_map_2025 = labels_full_2025.reshape(
    image_blur_2025.shape[:2]
)

# CENTROS ESPECTRAIS

centers_2025 = (
    kmeans_2025.cluster_centers_
)

# VOLTAR PARA ESCALA ORIGINAL

centers_original_2025 = (
    scaler_2025.inverse_transform(
        centers_2025
    )
)

# RGB DOS CLUSTERS

centers_rgb_2025 = (
    centers_original_2025[:, :3]
)
centers_rgb_2025 = np.clip(
    centers_rgb_2025 * 255,
    0,
    255
).astype(np.uint8)

# IMAGEM SEGMENTADA

segmented_2025 = np.zeros_like(
    rgb_vis_2025
)

# ÁGUA = AZUL

segmented_2025.reshape(
    (-1,3)
)[water_flat_2025] = [0,0,255]

# CORES DOS CLUSTERS

segmented_pixels_2025 = centers_rgb_2025[
    labels_valid_2025
]

segmented_2025.reshape(
    (-1,3)
)[valid_pixels_2025] = segmented_pixels_2025

# PLOT

fig, ax = plt.subplots(
    1,
    3,
    figsize=(20,8)
)

# RGB

ax[0].imshow(
    rgb_vis_2025
)
ax[0].set_title('RGB - 2025')
ax[0].axis('off')

# KMEANS

ax[1].imshow(
    segmented_2025
)
ax[1].set_title('KMeans - 2025')
ax[1].axis('off')

# MAPA DE CLASSES

ax[2].imshow(
    class_map_2025,
    cmap='terrain'
)
ax[2].set_title(
    'Mapa KMeans - 2025'
)
ax[2].axis('off')
plt.tight_layout()
plt.show()

"""# **[ANO 2] Visualização individual dos clusters KMeans**

Gera subplots para cada cluster identificado em 2025, aplicando máscara de transparência sobre a imagem RGB para destacar a distribuição espacial de cada classe, incluindo a separação da água e dos cinco clusters terrestres.
"""

# VISUALIZAÇÃO DOS CLUSTERS - 2025

n_clusters = 5

# SUBPLOTS

fig, ax = plt.subplots(
    2,
    3,
    figsize=(18,10)
)

ax = ax.ravel()

# LOOP DOS CLUSTERS

for i in range(n_clusters + 1):

    # MÁSCARA DO CLUSTER

    cluster_mask = (
        class_map_2025 == i
    )

    # OVERLAY RGBA

    overlay = np.zeros(
        (
            class_map_2025.shape[0],
            class_map_2025.shape[1],
            4
        ),
        dtype=np.float32
    )

    # ESCURECER FORA DO CLUSTER

    overlay[..., 3] = (
        ~cluster_mask
    ) * 0.85

    # RGB

    ax[i].imshow(
        rgb_vis_2025
    )

    # OVERLAY

    ax[i].imshow(
        overlay
    )

    # TÍTULO

    if i == 0:
        title = 'Água'
    else:
        title = f'Cluster {i}'
    ax[i].set_title(title)
    ax[i].axis('off')

# REMOVER EIXOS SOBRANDO

for j in range(
    n_clusters + 1,
    len(ax)
):
    ax[j].axis('off')

# PLOT

plt.tight_layout()
plt.show()

"""# **[ANO 2] Reclassificação temática e estimativa de áreas**

Agrupa os clusters do KMeans em classes temáticas (água, areia, vegetação e urbanização), calcula a área ocupada por cada classe com base no tamanho do pixel e gera o mapa temático final com legenda quantitativa para o ano de 2025.
"""

# DEFINIÇÃO DAS CLASSES TEMÁTICAS - 2025
agua_2025 = [0]
areia_2025 = [3]
vegetacao_2025 = [1]
urbanizacao_2025 = [2,4,5]

# MAPA TEMÁTICO

thematic_map_2025 = np.zeros_like(
    class_map_2025
)

# ÁGUA = 0

for c in agua_2025:
    thematic_map_2025[
        class_map_2025 == c
    ] = 0

# AREIA = 1

for c in areia_2025:
    thematic_map_2025[
        class_map_2025 == c
    ] = 1

# VEGETAÇÃO = 2

for c in vegetacao_2025:
    thematic_map_2025[
        class_map_2025 == c
    ] = 2

# URBANIZAÇÃO = 3

for c in urbanizacao_2025:
    thematic_map_2025[
        class_map_2025 == c
    ] = 3

# CÁLCULO DE ÁREA

pixel_area = 100 # m²

area_agua_2025 = np.sum(
    thematic_map_2025 == 0
) * pixel_area

area_areia_2025 = np.sum(
    thematic_map_2025 == 1
) * pixel_area

area_vegetacao_2025 = np.sum(
    thematic_map_2025 == 2
) * pixel_area

area_urbanizacao_2025 = np.sum(
    thematic_map_2025 == 3
) * pixel_area

# CORES

colors = [
    'blue',     # água
    'khaki',    # areia
    'green',    # vegetação
    'gray'      # urbanização
]

cmap = ListedColormap(colors)

# PLOT

plt.figure(figsize=(10,10))
plt.imshow(
    thematic_map_2025,
    cmap=cmap,
    vmin=0,
    vmax=3
)
plt.title(
    'Mapa Temático - 2025'
)
plt.axis('off')

# LEGENDA

legend_elements = [
    Patch(
        facecolor='blue',
        label=f'Água ({area_agua_2025:,.0f} m²)'
    ),
    Patch(
        facecolor='khaki',
        label=f'Areia ({area_areia_2025:,.0f} m²)'
    ),
    Patch(
        facecolor='green',
        label=f'Vegetação ({area_vegetacao_2025:,.0f} m²)'
    ),
    Patch(
        facecolor='gray',
        label=f'Urbanização ({area_urbanizacao_2025:,.0f} m²)'
    )
]

plt.legend(
    handles=legend_elements,
    loc='upper right',
    fontsize=10,
    frameon=True
)
plt.tight_layout()
plt.show()

"""# **Análise de mudança temporal (ANO 1 vs ANO 2)**

Compara os mapas temáticos de 2019 e 2025 por meio de matriz de confusão, calcula a similaridade global entre as classes, converte os resultados para área (m²), gera uma matriz normalizada e visualiza as mudanças espaciais entre os períodos.
"""

# COMPARAÇÃO TEMPORAL 2019 vs 2025

# ACHATAR MAPAS

map_2019_flat = thematic_map_2019.flatten()
map_2025_flat = thematic_map_2025.flatten()

# PIXELS VÁLIDOS

valid = (
    (map_2019_flat >= 0)
    &
    (map_2025_flat >= 0)
)

map_2019_valid = map_2019_flat[valid]
map_2025_valid = map_2025_flat[valid]

# MATRIZ DE CONFUSÃO

cm = confusion_matrix(
    map_2019_valid,
    map_2025_valid
)

# CONVERSÃO PARA m²

pixel_area = 100
cm_m2 = cm * pixel_area

# MATRIZ NORMALIZADA

cm_norm = cm / cm.sum(
    axis=1,
    keepdims=True
)
cm_norm = np.nan_to_num(
    cm_norm
)

# ACURÁCIA GLOBAL

acc = accuracy_score(
    map_2019_valid,
    map_2025_valid
)

print('\nSIMILARIDADE GLOBAL:')
print(f'{acc*100:.2f}%')

# NOMES DAS CLASSES

class_names = [
    'Água',
    'Areia',
    'Vegetação',
    'Urbanização'
]

# PLOT

fig, ax = plt.subplots(
    1,
    2,
    figsize=(14,6)
)

# MATRIZ ABSOLUTA

disp1 = ConfusionMatrixDisplay(
    confusion_matrix=cm_m2,
    display_labels=class_names
)

disp1.plot(
    cmap='Blues',
    ax=ax[0],
    colorbar=True
)

ax[0].set_title(
    '2019 vs 2025 (m²)'
)
ax[0].set_xlabel('2025')
ax[0].set_ylabel('2019')

# MATRIZ NORMALIZADA

disp2 = ConfusionMatrixDisplay(
    confusion_matrix=cm_norm,
    display_labels=class_names
)

disp2.plot(
    cmap='Greens',
    ax=ax[1],
    values_format=".2f",
    colorbar=True
)

ax[1].set_title(
    '2019 vs 2025 (Normalizado)'
)
ax[1].set_xlabel('2025')
ax[1].set_ylabel('2019')
plt.tight_layout()
plt.show()

"""# **Mapa de mudanças e divergências temporais (ANO 1 → ANO 2)**

Identifica pixels que mudaram entre os mapas temáticos de 2019 e 2025, reconstrói o mapa binário de mudança, calcula as áreas de alteração e estabilidade e visualiza espacialmente as regiões de transformação ao longo do período.
"""

# MAPA DE DIVERGÊNCIAS 2019 vs 2025

# ACHATAR MAPAS

map_2019_flat = thematic_map_2019.flatten()
map_2025_flat = thematic_map_2025.flatten()

# PIXELS VÁLIDOS

valid = (
    (map_2019_flat >= 0)
    &
    (map_2025_flat >= 0)
)

# MAPA DE MUDANÇA

change_pixels = (
    map_2019_flat[valid]
    !=
    map_2025_flat[valid]
).astype(np.uint8)

# RECONSTRUIR FORMATO 2D

change_map = np.full(
    map_2019_flat.shape,
    -1
)
change_map[valid] = change_pixels
change_map = change_map.reshape(
    thematic_map_2019.shape
)

# ÁREA ALTERADA

pixel_area = 100 # m²
changed_area = np.sum(
    change_map == 1
) * pixel_area

unchanged_area = np.sum(
    change_map == 0
) * pixel_area

# PLOT

plt.figure(figsize=(10,10))

# 0 = sem mudança
# 1 = mudança

cmap_change = ListedColormap([
    'black',
    'red'
])

plt.imshow(
    change_map,
    cmap=cmap_change,
    vmin=0,
    vmax=1
)
plt.title(
    'Mudanças 2019 → 2025'
)
plt.axis('off')

# LEGENDA

legend_elements = [
    Patch(
        facecolor='black',
        label=f'Sem mudança ({unchanged_area:,.0f} m²)'
    ),
    Patch(
        facecolor='red',
        label=f'Mudança ({changed_area:,.0f} m²)'
    )
]

plt.legend(
    handles=legend_elements,
    loc='upper right',
    fontsize=10,
    frameon=True
)

plt.tight_layout()
plt.show()

"""# **Variação de área por classe (ANO 1 vs ANO 2)**

Calcula a área ocupada por cada classe temática nos dois anos, compara os valores entre 2019 e 2025 e resume as mudanças em termos de aumento, redução ou estabilidade para água, areia, vegetação e urbanização.
"""

# ÁREA DAS CLASSES - 2019

area_agua_2019 = np.sum(
    thematic_map_2019 == 0
) * pixel_area

area_areia_2019 = np.sum(
    thematic_map_2019 == 1
) * pixel_area

area_vegetacao_2019 = np.sum(
    thematic_map_2019 == 2
) * pixel_area

area_urbanizacao_2019 = np.sum(
    thematic_map_2019 == 3
) * pixel_area

# ÁREA DAS CLASSES - 2025

area_agua_2025 = np.sum(
    thematic_map_2025 == 0
) * pixel_area

area_areia_2025 = np.sum(
    thematic_map_2025 == 1
) * pixel_area

area_vegetacao_2025 = np.sum(
    thematic_map_2025 == 2
) * pixel_area

area_urbanizacao_2025 = np.sum(
    thematic_map_2025 == 3
) * pixel_area

# DIFERENÇAS

diff_agua = (
    area_agua_2025 -
    area_agua_2019
)

diff_areia = (
    area_areia_2025 -
    area_areia_2019
)

diff_vegetacao = (
    area_vegetacao_2025 -
    area_vegetacao_2019
)

diff_urbanizacao = (
    area_urbanizacao_2025 -
    area_urbanizacao_2019
)

# FUNÇÃO AUXILIAR

def describe_change(value):
    if value > 0:
        return f'aumentou {value:,.0f} m²'
    elif value < 0:
        return f'diminuiu {abs(value):,.0f} m²'
    else:
        return 'não mudou'

# RESULTADOS

print('\nVARIAÇÃO DE ÁREA (2019 → 2025)\n')
print(
    f'Água: {describe_change(diff_agua)}'
)
print(
    f'Areia: {describe_change(diff_areia)}'
)
print(
    f'Vegetação: {describe_change(diff_vegetacao)}'
)
print(
    f'Urbanização: {describe_change(diff_urbanizacao)}'
)