# -*- coding: utf-8 -*-
"""G2_notebook1_Visao-classica

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z6xO3236KCKGbY7j631xvYW0FmwCdQOH

# **Importação de Bibliotecas e Inicialização do Google Earth Engine**

Este bloco realiza a importação das bibliotecas necessárias para processamento análise de imagens, incluindo ferramentas para manipulação numérica, visualização gráfica, processamento digital de imagens e técnicas de classificação não supervisionada. Além disso, inicializa a conexão com o Google Earth Engine (GEE), permitindo o acesso e processamento de dados geoespaciais em nuvem.
"""

import ee
import geemap
import numpy as np
import matplotlib.pyplot as plt
import cv2
import matplotlib.patches as mpatches

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.mixture import GaussianMixture
from matplotlib.colors import ListedColormap
from matplotlib.patches import Patch
from sklearn.metrics import confusion_matrix
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt

ee.Authenticate()
ee.Initialize(project='trabalho-visao-grupo2')

"""# ▶ **Definição da Região de Interesse**

Este trecho define a região de interesse (ROI — Region of Interest) utilizada na análise. A área é delimitada por um retângulo geográfico especificado por coordenadas de longitude e latitude no Google Earth Engine, correspondendo à extensão espacial sobre a qual as imagens serão processadas.
"""

region = ee.Geometry.Rectangle([
   -48.646883,   # esquerda/baixo longitude ####################################
   -27.006631,   # esquerda/baixo latitude #####################################
   -48.595134,   # direita/cima longitude ######################################
   -26.968492    # direita/cima latitude #######################################
])

"""# **Função de Máscara de Nuvens para Imagens Sentinel-2**

Este bloco define uma função para remoção de nuvens e cirrus em imagens do satélite Sentinel-2 utilizando a banda de qualidade QA60. A função identifica pixels contaminados por nuvens por meio de operações bitwise, aplica uma máscara para manter apenas pixels válidos e realiza a normalização dos valores espectrais dividindo-os por 10.000.
"""

def mask_s2_clouds(image):

    qa = image.select('QA60')
    cloud_bit_mask  = 1 << 10
    cirrus_bit_mask = 1 << 11

    mask = (
        qa.bitwiseAnd(cloud_bit_mask).eq(0)
        .And(
            qa.bitwiseAnd(cirrus_bit_mask).eq(0)
        )
    )

    return (
        image
        .updateMask(mask)
        .divide(10000)
    )

"""# ▶ **Filtragem e Organização da Coleção de Imagens Sentinel-2**

Este trecho cria uma coleção de imagens Sentinel-2 (Surface Reflectance) harmonizadas no Google Earth Engine. As imagens são filtradas de acordo com a área de estudo, intervalo temporal definido e porcentagem máxima de cobertura de nuvens. Em seguida, a função de mascaramento de nuvens é aplicada a toda a coleção. Por fim, o código contabiliza o número total de imagens disponíveis e converte a coleção em uma lista para facilitar o acesso individual às cenas.
"""

dataset = (
    ee.ImageCollection('COPERNICUS/S2_SR_HARMONIZED')
    .filterBounds(region)
    .filterDate('2019-01-01', '2019-12-31') #DEFINIR PERÍODO DE TEMPO ##########
    .filter(
        ee.Filter.lt(
            'CLOUDY_PIXEL_PERCENTAGE', 15) #DEFINIR PORCENTAGEM DE NUVENS ######
    )
    .map(mask_s2_clouds)
)

n_images = dataset.size().getInfo()
print(f'Total de imagens: {n_images}')
image_list = dataset.toList(n_images)

"""# **Visualização da Coleção de Imagens na ROI**

Este bloco cria um mapa interativo utilizando a biblioteca geemap para visualização das imagens Sentinel-2 selecionadas. O mapa é centralizado na região de estudo e as imagens são adicionadas em composição RGB natural (bandas B4, B3 e B2), com parâmetros de contraste e brilho ajustados para melhor interpretação visual. Além disso, a área de interesse é destacada em vermelho, permitindo a inspeção espacial das cenas disponíveis.
"""

Map = geemap.Map()
Map.centerObject(region, 12)

vis = {
    'bands': ['B4', 'B3', 'B2'],
    'min': 0.02,
    'max': 0.20,
    'gamma': 1.2
}

for i in range(n_images):
    image = ee.Image(image_list.get(i))
    image_id = image.get('system:id').getInfo()
    print(i, image_id)
    Map.addLayer(image,vis,f'Imagem_{i}',False
    )

Map.addLayer(
    region,
    {'color': 'red'},
    'ROI'
)

Map

"""# ▶ **Seleção das Imagens para Composição Final**

Este bloco realiza a seleção manual das imagens consideradas mais adequadas para a análise. As imagens selecionadas são agrupadas em uma nova coleção e combinadas por meio de uma composição de mediana, reduzindo ruídos residuais e inconsistências atmosféricas.

Em seguida, a composição RGB é convertida do formato do Google Earth Engine para um array NumPy, possibilitando o processamento local em Python. O código também trata valores ausentes (NaN), normaliza os dados e aplica ajuste de contraste utilizando percentis, melhorando a visualização da imagem final exibida em formato RGB.
"""

selected_indexes = [6,7] # COLOCAR AQUI O ÍNDICE DAS IMAGENS ESCOLHIDAS ########

selected_images = []

print('\nIMAGENS ESCOLHIDAS:\n')

for idx in selected_indexes:
    img = ee.Image(image_list.get(idx))
    # ID da imagem
    image_id = img.id().getInfo()
    print(f'{idx} -> {image_id}')
    # adiciona na lista
    selected_images.append(img)

selected_collection = ee.ImageCollection(
    selected_images
)

# COMPOSIÇÃO FINAL (MEDIANA)
image_ee = selected_collection.median()

# CONVERTER RGB PARA NUMPY
image_rgb = geemap.ee_to_numpy(
    image_ee.select(['B4', 'B3', 'B2']),
    region=region,
    scale=10
)

# VERIFICAÇÃO
if image_rgb is None:
    raise ValueError(
        "Earth Engine retornou imagem vazia"
    )

# substitui NaN por zero
image_rgb = np.nan_to_num(image_rgb)

# NORMALIZAÇÃO
image_plot = image_rgb.astype(np.float32)

# percentis para melhorar contraste
p2, p98 = np.percentile(image_plot,(2, 98))

image_plot = np.clip((image_plot - p2) / (p98 - p2 + 1e-8), 0, 1)

# PLOT
plt.figure(figsize=(10, 10))
plt.imshow(image_plot)
plt.title('Imagem Final - Mediana')
plt.axis('off')
plt.tight_layout()
plt.show()

"""#**Cálculo de Índices Espectrais e Definição da Máscara de Água**

Este trecho calcula índices espectrais derivados das bandas do Sentinel-2, Este bloco calcula índices espectrais derivados das bandas do Sentinel-2, incluindo o NDVI (Normalized Difference Vegetation Index), relacionado à identificação de vegetação; o MNDWI (Modified Normalized Difference Water Index), utilizado para realce de corpos hídricos; e o NDBI (Normalized Difference Built-up Index), voltado à detecção de áreas urbanizadas.

Além disso, é criada uma máscara espectral de água com base em limiares aplicados ao MNDWI e NDVI, permitindo separar previamente os pixels associados a corpos d’água antes da etapa de clusterização. Essa abordagem híbrida reduz ambiguidades espectrais entre água e superfícies terrestres, contribuindo para melhorar a segmentação das demais classes.

Posteriormente, as bandas espectrais e os índices calculados são combinados em um empilhamento multiespectral (stack), ampliando a capacidade de discriminação entre diferentes tipos de cobertura da superfície. Por fim, a imagem é recortada à área de estudo, mascarada para garantir consistência espacial entre as bandas e convertida para o formato NumPy para processamento em Python.
"""

# ÍNDICES ESPECTRAIS
ndvi = image_ee.normalizedDifference(['B8', 'B4']).rename('NDVI');
mndwi = image_ee.normalizedDifference(['B3', 'B11']).rename('MNDWI');
ndbi = image_ee.normalizedDifference(['B11', 'B8']).rename('NDBI');

# MÁSCARA DE ÁGUA
water_mask = (
    (mndwi.gt(0.05))
    .And(ndvi.lt(0.1))
)

# STACK MULTIESPECTRAL
image_stack = image_ee.select([
    'B2', 'B3', 'B4', 'B8', 'B11'
]).addBands([
    ndvi.multiply(2),
    mndwi.multiply(3),
    ndbi.multiply(2)
])

image_stack = image_stack.clip(region)
image_stack = image_stack.updateMask(image_stack.mask().reduce(ee.Reducer.min()))

# CONVERTER PARA NUMPY
image = geemap.ee_to_numpy(
    image_stack,
    region=region,
    scale=10
)

water_np = geemap.ee_to_numpy(
    water_mask,
    region=region,
    scale=10
)

water_np = water_np.astype(bool)

"""#**Pré-processamento, Suavização e Preparação dos Dados para Clusterização Terrestre**

Este bloco realiza etapas de verificação e pré-processamento da imagem multiespectral antes da aplicação dos algoritmos de classificação não supervisionada. Inicialmente, são executadas validações para garantir que a imagem não esteja vazia, mascarada ou sem variação espectral, evitando inconsistências durante o processamento.

Em seguida, cada banda é normalizada individualmente com base nos percentis 2 e 98, reduzindo a influência de valores extremos e padronizando a distribuição espectral dos dados. Posteriormente, aplica-se um filtro Gaussiano para suavização espacial da imagem, minimizando ruídos e pequenas variações entre pixels adjacentes.

A composição RGB é então preparada para visualização, incluindo ajuste de contraste e conversão para formato compatível com exibição gráfica. Por fim, os dados multiespectrais são reorganizados em formato vetorial, removendo pixels inválidos e realizando a padronização estatística das variáveis com StandardScaler, etapa necessária para otimizar o desempenho dos algoritmos de clusterização.
"""

# VERIFICAÇÃO INICIAL
if image is None:
    raise ValueError(
        "Earth Engine retornou imagem vazia"
    )

print('\nINFORMAÇÕES DA IMAGEM:\n')
print(f'Shape: {image.shape}')
print(f'Mínimo: {np.nanmin(image)}')
print(f'Máximo: {np.nanmax(image)}')
print(f'Pixels não nulos: {np.count_nonzero(image)}')

if np.count_nonzero(image) == 0:
    raise ValueError(
        "Imagem completamente vazia"
    )

if np.nanmax(image) == np.nanmin(image):
    raise ValueError(
        "Imagem sem variação espectral"
    )

# VERIFICAR PIXELS VÁLIDOS
if np.count_nonzero(image) == 0:
    raise ValueError(
        "Imagem totalmente vazia ou mascarada"
    )

# NORMALIZAÇÃO POR BANDA
image = image.astype(np.float32)

for b in range(image.shape[2]):
    band = image[:, :, b]
    p2 = np.nanpercentile(band, 2)
    p98 = np.nanpercentile(band, 98)
    den = p98 - p2
    if den > 1e-8:
        band = np.clip(
            (band - p2) / den,
            0,
            1
        )
    else:
        print(f'Banda {b} constante ou sem variação')
        band = np.zeros_like(band)
    image[:, :, b] = band


# SUAVIZAÇÃO
image_blur = cv2.GaussianBlur(
    image,
    (5, 5), # DEFINIR O NÍVEL DE BLUR ##########################################
    0
)

# RGB PARA VISUALIZAÇÃO
rgb_vis = image_blur[:, :, :3]

# garante intervalo válido antes de converter
rgb_vis = np.clip(rgb_vis, 0, 1)

# melhora contraste perceptual
rgb_vis = rgb_vis ** 0.8
rgb_vis = (rgb_vis * 255).astype(np.uint8)

# PREPARAÇÃO KMEANS
pixels = image_blur.reshape(
    (-1, image_blur.shape[2])
)

print('\nFORMATO DOS PIXELS:')
print(pixels.shape)

# REMOVER ÁGUA DA CLUSTERIZAÇÃO
water_flat = water_np.flatten()

pixel_sum = np.sum(
    np.abs(pixels),
    axis=1
)

valid_pixels = (
    (pixel_sum > 0) &
    (~water_flat)
)

pixels_valid = pixels[valid_pixels]
print('\nPIXELS VÁLIDOS:')
print(pixels_valid.shape)
if pixels_valid.shape[0] == 0:
  raise ValueError('Nenhum pixel válido encontrado')


# PADRONIZAÇÃO
scaler = StandardScaler()
pixels_scaled = scaler.fit_transform(pixels_valid)

"""# ▶ **TESTE 1: K-MEANS**

Este bloco aplica o algoritmo de classificação não supervisionada K-Means aos Este bloco aplica o algoritmo de classificação não supervisionada K-Means apenas aos pixels terrestres da imagem, após a remoção prévia das regiões identificadas como água pela máscara espectral baseada em índices. Essa abordagem híbrida reduz ambiguidades espectrais entre água e superfícies costeiras adjacentes, permitindo que os clusters sejam dedicados exclusivamente à segmentação das feições terrestres.

Após o treinamento do modelo, os rótulos gerados para os pixels válidos são reorganizados para reconstruir o mapa espacial de classes correspondente à imagem original. Os pixels classificados previamente como água recebem uma classe fixa independente da clusterização, enquanto os agrupamentos terrestres são numerados separadamente.

Em seguida, os centroides espectrais de cada cluster são convertidos novamente para a escala original dos dados, possibilitando a criação de uma representação RGB segmentada. Para facilitar a interpretação visual, a classe de água é representada em azul, enquanto os demais clusters recebem colorações associadas aos seus centroides espectrais.

Por fim, são exibidos a composição RGB original, a segmentação produzida pelo K-Means e o mapa espacial das classes, permitindo avaliar visualmente a distribuição dos agrupamentos espectrais sobre a área de estudo.
"""

kmeans = KMeans(
    n_clusters=4, # DEFINIR QUANTIDADE DE CLUSTERS TERRESTRES
    random_state=100,
    n_init=100
)

kmeans.fit(pixels_scaled)

labels_valid = kmeans.labels_

# RECONSTRUIR MAPA
labels_full = np.full(
    pixels.shape[0],
    -1
)

# água recebe classe fixa
labels_full[water_flat] = 0

# clusters terrestres começam em 1
labels_full[valid_pixels] = labels_valid + 1

class_map = labels_full.reshape(
    image_blur.shape[:2]
)

# CENTROS ESPECTRAIS
centers = kmeans.cluster_centers_

# volta para escala original
centers_original = scaler.inverse_transform(
    centers
)

# RGB PARA VISUALIZAÇÃO

centers_rgb = centers_original[:, :3]

centers_rgb = np.clip(
    centers_rgb * 255,
    0,
    255
).astype(np.uint8)

# cria imagem segmentada
segmented = np.zeros_like(rgb_vis)

# água aparece azul
segmented.reshape(
    (-1, 3)
)[water_flat] = [0, 0, 255]

# pixels terrestres recebem cores dos clusters
segmented_pixels = centers_rgb[
    labels_valid
]

segmented.reshape(
    (-1, 3)
)[valid_pixels] = segmented_pixels

# PLOT
fig, ax = plt.subplots(
    1,
    3,
    figsize=(20,8)
)

ax[0].imshow(rgb_vis)

ax[0].set_title(
    'RGB'
)

ax[0].axis('off')

# ======================
# KMEANS RGB
# ======================

ax[1].imshow(segmented)

ax[1].set_title(
    'KMeans'
)

ax[1].axis('off')

# ======================
# MAPA DE CLASSES
# ======================

ax[2].imshow(
    class_map,
    cmap='terrain'
)

ax[2].set_title(
    'Mapa KMeans'
)

ax[2].axis('off')

plt.tight_layout()

plt.show()

"""#▶ K-MEANS: Visualização Individual dos Clusters para Classificação

Este bloco gera uma visualização individual de cada cluster identificado pelo Este bloco apresenta a distribuição espacial das classes identificadas após a aplicação da máscara espectral de água e da clusterização K-Means. Inicialmente, a classe correspondente à água, previamente definida por critérios espectrais, é exibida separadamente das classes terrestres.

Para cada agrupamento terrestre gerado pelo algoritmo K-Means, é criada uma máscara espacial destacando apenas os pixels pertencentes ao respectivo cluster, enquanto as demais regiões da imagem são escurecidas com uma camada semitransparente. Essa abordagem facilita a interpretação visual da segmentação e permite analisar individualmente a distribuição espacial dos diferentes agrupamentos espectrais.

A visualização também auxilia na identificação das feições da superfície representadas por cada cluster, contribuindo para a interpretação temática e validação qualitativa dos resultados da classificação não supervisionada.
"""

# =====================================================
# VISUALIZAÇÃO DOS CLUSTERS SOBRE O RGB
# =====================================================

n_clusters = 4  # QUANTIDADE DE CLUSTERS TERRESTRES ############################

fig, ax = plt.subplots(
    3, # QUANTIDADE DE LINHAS NO PLOT ##########################################
    2, # QUANTIDADE DE COLUNAS NO PLOT #########################################
    figsize=(18,10)
)

ax = ax.ravel()

for i in range(n_clusters + 1):

    # máscara do cluster
    cluster_mask = (class_map == i)

    # cria overlay RGBA
    overlay = np.zeros(
        (
            class_map.shape[0],
            class_map.shape[1],
            4
        ),
        dtype=np.float32
    )

    # pixels fora do cluster ficam escurecidos
    overlay[..., 3] = (~cluster_mask) * 0.85

    # RGB de fundo
    ax[i].imshow(rgb_vis)

    # overlay escuro
    ax[i].imshow(overlay)

    # título
    if i == 0:
        title = 'Água'
    else:
        title = f'Cluster {i}'

    ax[i].set_title(title)

    ax[i].axis('off')

# remove eixo vazio caso sobre subplot
for j in range(n_clusters + 1, len(ax)):
    ax[j].axis('off')

plt.tight_layout()

plt.show()

"""#▶ K-MEANS: Reclassificação Temática e Cálculo das Áreas das Classes

Este bloco realiza a interpretação temática dos clusters gerados pelo algoritmo Este bloco realiza a construção do mapa temático final a partir dos resultados da clusterização K-Means, incorporando a separação prévia da classe água obtida por meio da máscara espectral baseada no MNDWI. Dessa forma, a água é tratada como uma classe fixa (independente da clusterização), enquanto os demais pixels são agrupados em classes terrestres.

A partir do mapa de classes gerado, os clusters são reagrupados em categorias temáticas de interesse — água, areia, vegetação e urbanização — permitindo a interpretação física dos resultados espectrais. Em seguida, é calculada a área ocupada por cada classe com base na resolução espacial da imagem, considerando a área correspondente a cada pixel.

Por fim, o mapa temático é visualizado com uma paleta de cores específica para cada classe e acompanhado de uma legenda contendo as áreas estimadas, permitindo a análise espacial e quantitativa da distribuição das feições de cobertura da superfície na área de estudo.
"""

# DEFINIÇÃO DAS CLASSES TEMÁTICAS (ÁGUA FIXA)

agua = [0] # ÁGUA FIXA (MÁSCARA)
areia = [4] # CLUSTERS QUE REPRESENTAM AREIA ###################################
vegetacao = [2] # CLUSTERS QUE REPRESENTAM VEGETAÇÃO ###########################
urbanizacao = [1,3] # CLUSTERS QUE REPRESENTAM URBANIZAÇÃO #####################


# CRIAR MAPA TEMÁTICO

thematic_map = np.zeros_like(class_map)

# Água = 0
for c in agua:
    thematic_map[class_map == c] = 0

# Areia = 1
for c in areia:
    thematic_map[class_map == c] = 1

# Vegetação = 2
for c in vegetacao:
    thematic_map[class_map == c] = 2

# Urbanização = 3
for c in urbanizacao:
    thematic_map[class_map == c] = 3

# CÁLCULO DE ÁREA

pixel_area = 100  # m² (10m x 10m)

area_agua = np.sum(thematic_map == 0) * pixel_area
area_areia = np.sum(thematic_map == 1) * pixel_area
area_vegetacao = np.sum(thematic_map == 2) * pixel_area
area_urbanizacao = np.sum(thematic_map == 3) * pixel_area


# CORES DAS CLASSES

colors = [
    'blue',        # Água
    'khaki',       # Areia
    'green',       # Vegetação
    'gray'         # Urbanização
]

cmap = ListedColormap(colors)

# PLOT

plt.figure(figsize=(10, 10))

plt.imshow(
    thematic_map,
    cmap=cmap,
    vmin=0,
    vmax=3
)

plt.title('Mapa Temático - KMeans (com máscara de água)')

plt.axis('off')

# LEGENDA COM ÁREA

legend_elements = [

    Patch(
        facecolor='blue',
        label=f'Água ({area_agua:,.0f} m²)'
    ),

    Patch(
        facecolor='khaki',
        label=f'Areia ({area_areia:,.0f} m²)'
    ),

    Patch(
        facecolor='green',
        label=f'Vegetação ({area_vegetacao:,.0f} m²)'
    ),

    Patch(
        facecolor='gray',
        label=f'Urbanização ({area_urbanizacao:,.0f} m²)'
    )
]

plt.legend(
    handles=legend_elements,
    loc='upper right',
    fontsize=10,
    frameon=True
)

plt.tight_layout()
plt.show()

"""#▶ **TESTE 2: GMM**

Este bloco aplica o algoritmo Gaussian Mixture Model (GMM) para a classificação não supervisionada dos pixels terrestres da imagem, após a remoção prévia das áreas identificadas como água por meio da máscara espectral baseada no MNDWI. Essa abordagem híbrida permite que o modelo probabilístico se concentre exclusivamente na variabilidade espectral das superfícies terrestres, evitando a interferência de assinaturas espectrais típicas de corpos d’água.

Após o ajuste do modelo, os rótulos obtidos para os pixels válidos são reorganizados para reconstrução do mapa espacial de classes. Em seguida, os pixels classificados como água são reinseridos como uma classe fixa, enquanto os agrupamentos terrestres são numerados a partir da saída do modelo.

Os centróides espectrais estimados pelo GMM são convertidos de volta para a escala original dos dados, permitindo a geração de uma representação RGB segmentada. Por fim, são exibidas a composição RGB original, a segmentação resultante do GMM e o mapa espacial de classes, possibilitando a análise visual da distribuição dos agrupamentos espectrais na área de estudo.
"""

gmm = GaussianMixture(
    n_components=4,  # QUANTIDADE DE CLUSTERS TERRESTRES #######################
    covariance_type='full',
    random_state=100
)

gmm.fit(pixels_scaled)

labels_valid_gmm = gmm.predict(pixels_scaled)

# RECONSTRUIR MAPA

labels_full_gmm = np.full(
    pixels.shape[0],
    -1
)

# água recebe classe fixa
labels_full_gmm[water_flat] = 0

# clusters terrestres começam em 1
labels_full_gmm[valid_pixels] = labels_valid_gmm + 1

class_map_gmm = labels_full_gmm.reshape(
    image_blur.shape[:2]
)

# CENTROS ESPECTRAIS

centers_gmm = gmm.means_

centers_gmm_original = scaler.inverse_transform(
    centers_gmm
)

# RGB PARA VISUALIZAÇÃO

centers_rgb_gmm = centers_gmm_original[:, :3]

centers_rgb_gmm = np.clip(
    centers_rgb_gmm * 255,
    0,
    255
).astype(np.uint8)

segmented_gmm = np.zeros_like(rgb_vis)

# água azul
segmented_gmm.reshape(
    (-1, 3)
)[water_flat] = [0, 0, 255]

# clusters terrestres
segmented_pixels_gmm = centers_rgb_gmm[
    labels_valid_gmm
]

segmented_gmm.reshape(
    (-1, 3)
)[valid_pixels] = segmented_pixels_gmm

# PLOT

fig, ax = plt.subplots(
    1,
    3,
    figsize=(20,8)
)

# RGB ORIGINAL
ax[0].imshow(rgb_vis)
ax[0].set_title('RGB')
ax[0].axis('off')

# GMM SEGMENTADO
ax[1].imshow(segmented_gmm)
ax[1].set_title('GMM')
ax[1].axis('off')

# MAPA DE CLASSES
ax[2].imshow(class_map_gmm, cmap='terrain')
ax[2].set_title('Mapa GMM')
ax[2].axis('off')

plt.tight_layout()
plt.show()

"""#▶ GMM: Visualização Individual dos Clusters para Classificação

Este bloco realiza a construção do mapa temático final a partir dos resultados obtidos com o modelo Gaussian Mixture Model (GMM), incorporando a separação prévia da classe água por meio de máscara espectral baseada no MNDWI. Dessa forma, a água é tratada como uma classe fixa independente do processo de clusterização, enquanto os demais pixels correspondem exclusivamente às superfícies terrestres.

A partir dos clusters gerados pelo GMM, os rótulos são reorganizados em classes temáticas de interesse (areia, vegetação e urbanização), com base na interpretação espectral de cada agrupamento. Essa etapa permite transformar os resultados numéricos da clusterização em informações geográficas e fisicamente interpretáveis.

Em seguida, é calculada a área ocupada por cada classe, considerando a resolução espacial da imagem e a área correspondente a cada pixel. O mapa temático resultante é visualizado com uma paleta de cores associada a cada classe e acompanhado de uma legenda com as áreas estimadas, permitindo a análise quantitativa e espacial da distribuição das diferentes feições de cobertura da superfície na área de estudo.
"""

# VISUALIZAÇÃO DOS CLUSTERS SOBRE O RGB - GMM

n_clusters = 4  # QUANTIDADE DE CLUSTERS TERRESTRES ############################

total_plots = n_clusters + 1  # + água

fig, ax = plt.subplots(
    2, # QUANTIDADE DE LINHAS NO PLOT ##########################################
    3, # QUANTIDADE DE COLUNAS NO PLOT #########################################
    figsize=(18,10)
)

ax = ax.ravel()

for i in range(total_plots):

    # máscara do cluster
    cluster_mask = (class_map_gmm == i)

    # overlay RGBA
    overlay = np.zeros(
        (
            class_map_gmm.shape[0],
            class_map_gmm.shape[1],
            4
        ),
        dtype=np.float32
    )

    overlay[..., 3] = (~cluster_mask) * 0.85

    ax[i].imshow(rgb_vis)
    ax[i].imshow(overlay)

    if i == 0:
        title = "Água"
    else:
        title = f"Cluster GMM {i}"

    ax[i].set_title(title)
    ax[i].axis('off')

# remove eixos vazios
for j in range(total_plots, len(ax)):
    ax[j].axis('off')

plt.tight_layout()
plt.show()

"""#▶ GMM: Reclassificação Temática e Cálculo das Áreas das Classes

Este bloco realiza a interpretação temática dos clusters produzidos pelo modelo Gaussian Mixture Model (GMM), associando os agrupamentos espectrais às classes de cobertura da superfície definidas pelo usuário, como água, areia, vegetação e urbanização. A partir dessa correspondência, é construído um mapa temático contendo as classes finais de interesse.

Em seguida, o código calcula a área ocupada por cada classe com base na resolução espacial da imagem Sentinel-2, considerando a área correspondente a cada pixel. Posteriormente, são definidas cores específicas para representação visual das classes e gerado o mapa temático final do GMM.

Por fim, é adicionada uma legenda contendo as áreas calculadas para cada classe temática, permitindo a análise quantitativa e espacial dos resultados produzidos pelo modelo probabilístico de classificação não supervisionada.
"""

# DEFINIÇÃO DAS CLASSES TEMÁTICAS - GMM (AJUSTADO)

agua = [0] # ÁGUA FIXA (MÁSCARA)
areia = [4] # CLUSTERS QUE REPRESENTAM AREIA ###################################
vegetacao = [2] # CLUSTERS QUE REPRESENTAM VEGETAÇÃO #########################
urbanizacao = [1,3] # CLUSTERS QUE REPRESENTAM URBANIZAÇÃO #####################

# CRIAR MAPA TEMÁTICO

thematic_map_gmm = np.zeros_like(class_map_gmm)

for c in agua:
    thematic_map_gmm[class_map_gmm == c] = 0

for c in areia:
    thematic_map_gmm[class_map_gmm == c] = 1

for c in vegetacao:
    thematic_map_gmm[class_map_gmm == c] = 2

for c in urbanizacao:
    thematic_map_gmm[class_map_gmm == c] = 3

# CÁLCULO DE ÁREA

pixel_area = 100  # m² (10m x 10m)

area_agua = np.sum(thematic_map_gmm == 0) * pixel_area
area_areia = np.sum(thematic_map_gmm == 1) * pixel_area
area_vegetacao = np.sum(thematic_map_gmm == 2) * pixel_area
area_urbanizacao = np.sum(thematic_map_gmm == 3) * pixel_area

# CORES

colors = [
    'blue',
    'khaki',
    'green',
    'gray'
]

cmap = ListedColormap(colors)

# PLOT

plt.figure(figsize=(10,10))

plt.imshow(
    thematic_map_gmm,
    cmap=cmap,
    vmin=0,
    vmax=3
)

plt.title('Mapa Temático - GMM (com máscara de água)')

plt.axis('off')

legend_elements = [

    Patch(facecolor='blue', label=f'Água ({area_agua:,.0f} m²)'),
    Patch(facecolor='khaki', label=f'Areia ({area_areia:,.0f} m²)'),
    Patch(facecolor='green', label=f'Vegetação ({area_vegetacao:,.0f} m²)'),
    Patch(facecolor='gray', label=f'Urbanização ({area_urbanizacao:,.0f} m²)')
]

plt.legend(
    handles=legend_elements,
    loc='upper right',
    fontsize=10,
    frameon=True
)

plt.tight_layout()
plt.show()

# COMBINAÇÃO DOS MAPAS
# Código = KMeans * 4 + GMM

comparison_map = thematic_map * 4 + thematic_map_gmm

# NOMES DAS CLASSES

class_names = [
    'Água',
    'Areia',
    'Vegetação',
    'Urbanização'
]

# CORES
# Concordâncias = branco
# Divergências = cores

colors = [

    # KMeans = Água
    '#FFFFFF',   # Água = Água
    '#00BFFF',   # Água vs. Areia
    '#1E90FF',   # Água vs. Vegetação
    '#0000CD',   # Água vs. Urbanização

    # KMeans = Areia
    '#FFD700',   # Areia vs. Água
    '#FFFFFF',   # Areia = Areia
    '#FF8C00',   # Areia vs. Vegetação
    '#FF4500',   # Areia vs. Urbanização

    # KMeans = Vegetação
    '#7CFC00',   # Vegetação vs. Água
    '#32CD32',   # Vegetação vs. Areia
    '#FFFFFF',   # Vegetação = Vegetação
    '#006400',   # Vegetação vs. Urbanização

    # KMeans = Urbanização
    '#FF69B4',   # Urbanização vs. Água
    '#FF0000',   # Urbanização vs. Areia
    '#800080',   # Urbanização vs. Vegetação
    '#FFFFFF'    # Urbanização = Urbanização

]

cmap = ListedColormap(colors)

# PLOT

fig, ax = plt.subplots(figsize=(12, 10))

ax.imshow(
    comparison_map,
    cmap=cmap,
    vmin=0,
    vmax=15
)

ax.set_title('Mapa de Divergência entre K-Means e GMM', fontsize=14)

ax.set_xticks([])
ax.set_yticks([])

legend_elements = []

present_codes = np.unique(comparison_map)

for code in present_codes:

    # Ignora concordâncias
    if code in [0, 5, 10, 15]:
        continue

    kmeans_class = code // 4
    gmm_class = code % 4

    legend_elements.append(
        Patch(
            facecolor=colors[code],
            edgecolor='black',
            label=f'{class_names[kmeans_class]} vs. {class_names[gmm_class]}'
        )
    )

if legend_elements:
    ax.legend(
        handles=legend_elements,
        title='Divergências',
        loc='upper right',
        fontsize=9,
        title_fontsize=10,
        framealpha=1,
        facecolor='white'
    )

plt.tight_layout()
plt.show()

"""# **Matriz de Confusão Espacial entre K-Means e GMM (em m²)**

Este bloco apresenta a comparação espacial entre os resultados obtidos pelos algoritmos K-Means e Gaussian Mixture Model (GMM), a partir dos mapas temáticos gerados após a remoção prévia da classe água. A análise é realizada por meio de uma matriz de confusão, na qual cada elemento representa a área (em metros quadrados) de concordância ou divergência entre as classes atribuídas por ambos os métodos.

A matriz é construída a partir do cruzamento pixel a pixel entre os mapas classificados, considerando apenas os pixels válidos (excluindo valores mascarados ou não classificados). Em seguida, os valores são convertidos de número de pixels para área real, utilizando a resolução espacial da imagem (10 m × 10 m por pixel), permitindo uma interpretação quantitativa mais consistente.

A acurácia global entre os métodos é calculada com base na proporção de pixels coincidentes, fornecendo uma medida geral de similaridade entre as segmentações. A matriz resultante é apresentada com rótulos temáticos consistentes (água, areia, vegetação e urbanização), e com eixos identificando claramente os métodos comparados (KMeans e GMM), permitindo uma avaliação direta das diferenças espaciais entre as abordagens de clusterização.
"""

# =====================================================
# ACHATAR MAPAS
# =====================================================

kmeans_flat = thematic_map.flatten()
gmm_flat = thematic_map_gmm.flatten()

# =====================================================
# REMOVER PIXELS INVÁLIDOS
# =====================================================

valid = (
    (kmeans_flat >= 0) &
    (gmm_flat >= 0)
)

kmeans_valid = kmeans_flat[valid]
gmm_valid = gmm_flat[valid]

# =====================================================
# MATRIZ DE CONFUSÃO (PIXELS)
# =====================================================

cm = confusion_matrix(
    kmeans_valid,
    gmm_valid
)

# =====================================================
# CONVERSÃO PARA m²
# =====================================================

pixel_area = 100  # m² (10m x 10m)

cm_m2 = cm * pixel_area

# =====================================================
# ACURÁCIA GLOBAL
# =====================================================

acc = accuracy_score(
    kmeans_valid,
    gmm_valid
)

print('\nACURÁCIA ENTRE MÉTODOS:')
print(f'{acc*100:.2f}%')

# =====================================================
# NOMES DAS CLASSES
# =====================================================

class_names = [
    'Água',
    'Areia',
    'Vegetação',
    'Urbanização'
]

# =====================================================
# PLOT DA MATRIZ DE CONFUSÃO
# =====================================================

fig, ax = plt.subplots(figsize=(8, 8))

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm_m2,
    display_labels=class_names
)

disp.plot(
    cmap='Blues',
    ax=ax,
    colorbar=True
)

plt.title('Matriz de Confusão (em m²)\nKMeans vs GMM')

# =====================================================
# NOMES DOS EIXOS (CORRETO PARA COMPARAÇÃO)
# =====================================================

ax.set_xlabel('GMM')
ax.set_ylabel('KMeans')

plt.tight_layout()
plt.show()

# =====================================================
# MATRIZ DE CONFUSÃO NORMALIZADA
# =====================================================

cm_norm = confusion_matrix(
    kmeans_valid,
    gmm_valid,
    normalize='true'
)

fig, ax = plt.subplots(figsize=(8, 8))

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm_norm,
    display_labels=class_names
)

disp.plot(
    cmap='Blues',
    ax=ax,
    colorbar=True,
    values_format='.2f'
)

plt.title('Matriz de Confusão Normalizada\nKMeans vs GMM')

# =====================================================
# NOMES DOS EIXOS
# =====================================================

ax.set_xlabel('GMM')
ax.set_ylabel('KMeans')

plt.tight_layout()
plt.show()

# # =====================================================
# # EXPORTAR RGB COMPOSITE (GEOTIFF)
# # =====================================================

# rgb = image_ee.select(['B4', 'B3', 'B2'])

# geemap.ee_export_image(
#     rgb,
#     filename='rgb_composite.tif',
#     scale=10,
#     region=region,
#     file_per_band=False
# )

# print("Exportação finalizada!")

"""# **IMAGEM DE REFERÊNCIA: Importação e Suavização**

Este bloco realiza a importação da imagem temática de referência utilizada para comparação e validação dos resultados de classificação. Inicialmente, a imagem é carregada a partir de um arquivo raster no formato TIFF utilizando a biblioteca OpenCV.

Como o OpenCV realiza a leitura das imagens no padrão BGR, a composição é convertida para o sistema RGB, garantindo compatibilidade com as rotinas de visualização e análise utilizadas ao longo do processamento.

Em seguida, é aplicado um filtro Gaussiano para suavização espacial da imagem de referência, com o objetivo de reduzir ruídos e pequenas descontinuidades entre classes adjacentes. Essa etapa contribui para minimizar efeitos de borda e pequenas inconsistências espaciais que podem influenciar análises comparativas posteriores, como matrizes de confusão e métricas de concordância entre métodos de classificação.

Por fim, a imagem suavizada é exibida para verificação visual da composição temática utilizada como referência.
"""

# ref_rgb = cv2.imread("/content/rgb_composite_classes.tif")

# # OpenCV lê em BGR → converter para RGB
# ref_rgb = cv2.cvtColor(ref_rgb, cv2.COLOR_BGR2RGB)

# # BLUR PARA REDUZIR RUÍDOS

# ref_rgb = cv2.GaussianBlur(ref_rgb, (3,3), 0) # AJUSTAR BLUR ###################

# print(ref_rgb.shape)

# plt.imshow(ref_rgb)
# plt.axis("off")
# plt.show()

"""# **Construção do Mapa de Referência por Similaridade Espectral RGB**

Este bloco realiza a geração do mapa temático de referência (ground truth) a partir da classificação automática dos pixels da imagem RGB com base em similaridade espectral. Inicialmente, são verificadas as dimensões espaciais da imagem de referência e dos mapas classificados, garantindo compatibilidade entre os diferentes produtos utilizados nas etapas de validação.

Em seguida, são definidas as cores representativas de cada classe temática (água, areia, vegetação e áreas urbanas), utilizando valores RGB previamente estabelecidos. Essas cores funcionam como assinaturas espectrais de referência para a classificação dos pixels da imagem.

A classificação é realizada por meio do cálculo da distância euclidiana no espaço RGB entre cada pixel da imagem e as cores associadas às classes temáticas. Para cada pixel, é atribuída a classe cuja assinatura espectral apresenta menor distância, permitindo gerar automaticamente um mapa temático discreto a partir da composição colorida de referência.

Após a classificação inicial, é aplicado um filtro de mediana para reduzir ruídos espaciais e eliminar pequenas descontinuidades entre pixels isolados, produzindo um mapa temático mais homogêneo e espacialmente consistente.

Por fim, o mapa de referência resultante é visualizado utilizando uma paleta de cores padronizada e acompanhado de uma legenda temática, possibilitando sua utilização posterior em análises quantitativas de desempenho, matrizes de confusão e comparação entre os métodos de classificação empregados no estudo.
"""

# print("Ref:", ref_rgb.shape)
# print("KMeans:", thematic_map.shape)
# print("GMM:", thematic_map_gmm.shape)

# # CORES DE REFERÊNCIA

# class_colors = np.array([
#     [0, 30, 255],    # Água
#     [246, 255, 0],   # Areia
#     [0, 148, 10],    # Vegetação
#     [255, 150, 0]    # Urbano
# ])

# class_names = ['Água', 'Areia', 'Vegetação', 'Urbano']

# colors = ['blue', 'khaki', 'green', 'gray']

# # CÁLCULO DA DISTÂNCIA RGB

# h, w, _ = ref_rgb.shape

# pixels = ref_rgb.reshape(-1, 3)

# # distância euclidiana entre cada pixel e cada classe
# distances = np.linalg.norm(
#     pixels[:, np.newaxis] - class_colors,
#     axis=2
# )

# # classe mais próxima
# reference_map = np.argmin(distances, axis=1)

# reference_map = reference_map.reshape(h, w)

# # REMOVER RUÍDOS

# from scipy.ndimage import median_filter

# reference_map = median_filter(reference_map, size=3)

# # PLOT

# plt.figure(figsize=(8,8))

# plt.imshow(
#     reference_map,
#     cmap=ListedColormap(colors),
#     vmin=0,
#     vmax=3
# )

# plt.title("Mapa de Referência (Ground Truth)")
# plt.axis("off")

# legend_patches = [
#     mpatches.Patch(color=colors[i], label=class_names[i])
#     for i in range(len(class_names))
# ]

# plt.legend(
#     handles=legend_patches,
#     loc='upper right',
#     frameon=True,
#     fontsize=9
# )

# plt.tight_layout()
# plt.show()

"""# **Avaliação de Desempenho do K-Means em Relação ao Mapa de Referência**

Este bloco realiza a avaliação quantitativa dos resultados obtidos pelo algoritmo K-Means por meio da comparação com o mapa temático de referência (ground truth). Inicialmente, os mapas classificados e de referência são convertidos para formato vetorial unidimensional, permitindo a comparação pixel a pixel entre as classes atribuídas pelos diferentes produtos.

Em seguida, são removidos os pixels inválidos ou mascarados, garantindo que apenas regiões classificadas simultaneamente nos dois mapas sejam consideradas na análise. A partir desses dados, é construída uma matriz de confusão representando a concordância e divergência entre as classes do K-Means e da referência temática.

A matriz é apresentada em duas abordagens complementares. Na primeira, os valores são convertidos para área real (m²) com base na resolução espacial das imagens Sentinel-2, permitindo quantificar a extensão espacial de concordâncias e erros de classificação. Na segunda, a matriz é normalizada por classe de referência, fornecendo uma representação proporcional que facilita a interpretação relativa do desempenho do modelo em cada categoria temática.

Além disso, é calculada a acurácia global da classificação, correspondente à proporção total de pixels corretamente classificados em relação ao mapa de referência. Por fim, os resultados são visualizados graficamente com rótulos temáticos consistentes, permitindo analisar tanto o desempenho espacial absoluto quanto a distribuição relativa dos acertos e inconsistências entre a classificação K-Means e o ground truth.
"""

# # ACHATAR MAPAS

# kmeans_flat = thematic_map.flatten()
# ref_flat = reference_map.flatten()

# # REMOVER PIXELS INVÁLIDOS

# valid = (
#     (kmeans_flat >= 0) &
#     (ref_flat >= 0)
# )

# kmeans_valid = kmeans_flat[valid]
# ref_valid = ref_flat[valid]

# # MATRIZ DE CONFUSÃO (PIXELS)

# cm = confusion_matrix(
#     ref_valid,
#     kmeans_valid
# )

# # CONVERSÃO PARA ÁREA (m²)

# pixel_area = 100  # Sentinel-2 (10m x 10m)

# cm_m2 = cm * pixel_area

# # NORMALIZAÇÃO POR CLASSE (ÁREA RELATIVA)

# # cada linha = classe de referência
# cm_norm = cm / cm.sum(axis=1, keepdims=True)

# # proteção contra divisão por zero
# cm_norm = np.nan_to_num(cm_norm)

# # ACURÁCIA GLOBAL

# acc = accuracy_score(ref_valid, kmeans_valid)

# print('\nACURÁCIA GLOBAL (KMeans vs Referência):')
# print(f'{acc*100:.2f}%')

# # NOMES DAS CLASSES

# class_names = [
#     'Água',
#     'Areia',
#     'Vegetação',
#     'Urbanização'
# ]

# # PLOT 1 — MATRIZ EM m² (ABSOLUTA)

# fig, ax = plt.subplots(1, 2, figsize=(14, 6))

# disp1 = ConfusionMatrixDisplay(
#     confusion_matrix=cm_m2,
#     display_labels=class_names
# )

# disp1.plot(
#     cmap='Blues',
#     ax=ax[0],
#     colorbar=True
# )

# ax[0].set_title('Matriz de Confusão (m²)')
# ax[0].set_xlabel('KMeans')
# ax[0].set_ylabel('Referência')

# # PLOT 2 — MATRIZ NORMALIZADA (PROPORÇÃO POR CLASSE)

# disp2 = ConfusionMatrixDisplay(
#     confusion_matrix=cm_norm,
#     display_labels=class_names
# )

# disp2.plot(
#     cmap='Greens',
#     ax=ax[1],
#     values_format=".2f",
#     colorbar=True
# )

# ax[1].set_title('Matriz Normalizada (por classe)')
# ax[1].set_xlabel('KMeans')
# ax[1].set_ylabel('Referência')

# plt.tight_layout()
# plt.show()

"""# **Avaliação de Desempenho do GMM em Relação ao Mapa de Referência**

Este bloco realiza a avaliação quantitativa dos resultados produzidos pelo modelo Gaussian Mixture Model (GMM) por meio da comparação com o mapa temático de referência (ground truth). Inicialmente, os mapas classificados e de referência são convertidos para formato vetorial unidimensional, possibilitando a comparação direta entre as classes atribuídas em cada pixel.

Em seguida, são removidos os pixels inválidos ou mascarados, garantindo que apenas áreas classificadas simultaneamente nos dois mapas sejam consideradas na análise. A partir desses dados, é construída uma matriz de confusão que representa espacialmente as concordâncias e divergências entre o GMM e a referência temática.

Os resultados são apresentados em duas abordagens complementares. Na primeira, os valores da matriz são convertidos para área real (m²) utilizando a resolução espacial das imagens Sentinel-2, permitindo quantificar espacialmente os acertos e erros de classificação. Na segunda, a matriz é normalizada por classe de referência, fornecendo uma representação proporcional do desempenho do modelo em cada categoria temática.

Além disso, é calculada a acurácia global da classificação, correspondente à proporção total de pixels corretamente classificados em relação ao mapa de referência. Por fim, os resultados são exibidos graficamente com rótulos temáticos padronizados, permitindo avaliar de forma integrada o desempenho espacial absoluto e relativo do modelo GMM em comparação ao ground truth.
"""

# # ACHATAR MAPAS

# gmm_flat = thematic_map_gmm.flatten()
# ref_flat = reference_map.flatten()

# # REMOVER PIXELS INVÁLIDOS

# valid = (
#     (gmm_flat >= 0) &
#     (ref_flat >= 0)
# )

# gmm_valid = gmm_flat[valid]
# ref_valid = ref_flat[valid]

# # MATRIZ DE CONFUSÃO (PIXELS)

# cm = confusion_matrix(
#     ref_valid,
#     gmm_valid
# )

# # CONVERSÃO PARA ÁREA (m²)

# pixel_area = 100  # 10m x 10m

# cm_m2 = cm * pixel_area

# # NORMALIZAÇÃO POR CLASSE (ÁREA RELATIVA)

# cm_norm = cm / cm.sum(axis=1, keepdims=True)
# cm_norm = np.nan_to_num(cm_norm)

# # ACURÁCIA GLOBAL

# acc = accuracy_score(ref_valid, gmm_valid)

# print('\nACURÁCIA GLOBAL (GMM vs Referência):')
# print(f'{acc*100:.2f}%')

# # NOMES DAS CLASSES

# class_names = [
#     'Água',
#     'Areia',
#     'Vegetação',
#     'Urbanização'
# ]

# # PLOT 1 — m² (ABSOLUTO)

# fig, ax = plt.subplots(1, 2, figsize=(14, 6))

# disp1 = ConfusionMatrixDisplay(
#     confusion_matrix=cm_m2,
#     display_labels=class_names
# )

# disp1.plot(
#     cmap='Blues',
#     ax=ax[0],
#     colorbar=True
# )

# ax[0].set_title('GMM vs Referência (m²)')
# ax[0].set_xlabel('GMM')
# ax[0].set_ylabel('Referência')

# # PLOT 2 — NORMALIZADO

# disp2 = ConfusionMatrixDisplay(
#     confusion_matrix=cm_norm,
#     display_labels=class_names
# )

# disp2.plot(
#     cmap='Greens',
#     ax=ax[1],
#     values_format=".2f",
#     colorbar=True
# )

# ax[1].set_title('GMM vs Referência (Normalizado)')
# ax[1].set_xlabel('GMM')
# ax[1].set_ylabel('Referência')

# plt.tight_layout()
# plt.show()

"""# **Mapeamento Espacial das Divergências entre as Classificações e o Ground Truth**

Este bloco realiza a identificação e visualização espacial das divergências entre os resultados obtidos pelos métodos K-Means e GMM em relação ao mapa temático de referência (ground truth). Inicialmente, os mapas classificados e o mapa de referência são convertidos para formato vetorial unidimensional, permitindo a comparação direta entre as classes atribuídas a cada pixel.

Em seguida, são selecionados apenas os pixels válidos, excluindo regiões mascaradas ou não classificadas. A partir dessa filtragem, são gerados mapas binários de erro para cada método, nos quais pixels corretamente classificados recebem valor zero e pixels divergentes em relação à referência recebem valor um.

Posteriormente, os vetores de erro são reconstruídos no formato espacial bidimensional original, possibilitando a representação geográfica das regiões onde ocorreram inconsistências de classificação. Essa abordagem permite identificar padrões espaciais de erro e áreas específicas nas quais os algoritmos apresentam maior dificuldade de segmentação temática.

Os resultados são apresentados por meio de mapas de divergência, nos quais os pixels classificados incorretamente são destacados em vermelho, enquanto os pixels corretamente classificados permanecem transparentes. Essa visualização facilita a análise qualitativa do desempenho espacial dos modelos K-Means e GMM, permitindo comparar diretamente a distribuição dos erros em relação ao ground truth.
"""

# # ACHATAR MAPAS

# kmeans_flat = thematic_map.flatten()
# gmm_flat = thematic_map_gmm.flatten()
# ref_flat = reference_map.flatten()

# # PIXELS VÁLIDOS

# valid = (
#     (ref_flat >= 0) &
#     (kmeans_flat >= 0) &
#     (gmm_flat >= 0)
# )

# ref_valid = ref_flat[valid]
# kmeans_valid = kmeans_flat[valid]
# gmm_valid = gmm_flat[valid]

# # MAPAS DE ERRO (0 = acerto, 1 = erro)

# error_kmeans = (ref_valid != kmeans_valid).astype(np.uint8)
# error_gmm = (ref_valid != gmm_valid).astype(np.uint8)

# # RECONSTRUIR FORMATO 2D

# error_kmeans_map = np.full(ref_flat.shape, -1)
# error_gmm_map = np.full(ref_flat.shape, -1)

# error_kmeans_map[valid] = error_kmeans
# error_gmm_map[valid] = error_gmm

# error_kmeans_map = error_kmeans_map.reshape(reference_map.shape)
# error_gmm_map = error_gmm_map.reshape(reference_map.shape)

# # PLOT

# fig, ax = plt.subplots(1, 2, figsize=(14, 7))

# # cores: 0 = acerto (transparente), 1 = erro (vermelho)
# cmap_err = ListedColormap(['none', 'red'])

# # KMEANS ERRO

# im1 = ax[0].imshow(error_kmeans_map, cmap=cmap_err, vmin=0, vmax=1)
# ax[0].set_title('Divergência: Referência × KMeans')
# ax[0].axis('off')

# # GMM ERRO

# im2 = ax[1].imshow(error_gmm_map, cmap=cmap_err, vmin=0, vmax=1)
# ax[1].set_title('Divergência: Referência × GMM')
# ax[1].axis('off')

# plt.tight_layout()
# plt.show()