# -*- coding: utf-8 -*-
"""G2_notebook3_UNET.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OG0OqiIJ3cIfWUX8s-BoF6Hbdx1DFjIi
"""

!pip install torch torchvision geemap earthengine-api

"""# **Importação de Bibliotecas**

Além das bibliotecas clássicas de processamento, são importadas as
bibliotecas do PyTorch para construção e treinamento da U-Net, e
do scikit-learn para geração do pseudo ground truth e métricas.

"""

import ee
import geemap
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import cv2


# Scikit-learn (apenas para pseudo GT e métricas)
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, accuracy_score
from matplotlib.colors import ListedColormap
from matplotlib.patches import Patch
from matplotlib.patches import Rectangle
from scipy.ndimage import median_filter

# PyTorch — U-Net
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader, random_split

# Inicialização do GEE
ee.Authenticate()
ee.Initialize(project='trabalho-visao-grupo2')

print("PyTorch version:", torch.__version__)
print("GPU disponível:", torch.cuda.is_available())
DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print("Usando:", DEVICE)

"""# **Definição da Região de Interesse**

Mesma ROI do notebook anterior.

"""

region = ee.Geometry.Rectangle([
   -48.646883,   # esquerda/baixo longitude
   -27.006631,   # esquerda/baixo latitude
   -48.595134,   # direita/cima longitude
   -26.968492    # direita/cima latitude
])

"""# **Máscara de Nuvens (Sentinel-2)**

"""

def mask_s2_clouds(image):
    qa = image.select('QA60')
    cloud_bit_mask  = 1 << 10
    cirrus_bit_mask = 1 << 11
    mask = (
        qa.bitwiseAnd(cloud_bit_mask).eq(0)
        .And(qa.bitwiseAnd(cirrus_bit_mask).eq(0))
    )
    return image.updateMask(mask).divide(10000)

"""# **Filtragem da Coleção Sentinel-2 e Composição Mediana**

"""

dataset = (
    ee.ImageCollection('COPERNICUS/S2_SR_HARMONIZED')
    .filterBounds(region)
    .filterDate('2019-01-01', '2019-12-31')
    .filter(ee.Filter.lt('CLOUDY_PIXEL_PERCENTAGE', 15))
    .map(mask_s2_clouds)
)

n_images = dataset.size().getInfo()
print(f'Total de imagens: {n_images}')
image_list = dataset.toList(n_images)

# Mesmas imagens do notebook anterior
selected_indexes = [6, 7]
selected_images = [ee.Image(image_list.get(i)) for i in selected_indexes]
selected_collection = ee.ImageCollection(selected_images)
image_ee = selected_collection.median()

# RGB para visualização
image_rgb = geemap.ee_to_numpy(
    image_ee.select(['B4', 'B3', 'B2']),
    region=region, scale=10
)
image_rgb = np.nan_to_num(image_rgb).astype(np.float32)
p2, p98 = np.percentile(image_rgb, (2, 98))
image_plot = np.clip((image_rgb - p2) / (p98 - p2 + 1e-8), 0, 1)

plt.figure(figsize=(10, 10))
plt.imshow(image_plot)
plt.title('Imagem Final - Mediana (RGB)')
plt.axis('off')
plt.tight_layout()
plt.show()

"""# **Índices Espectrais e Stack Multiespectral**

Calculamos NDVI, MNDWI e NDBI e empilhamos com as bandas originais.
Esse stack de 8 canais será a entrada da U-Net.

"""

ndvi  = image_ee.normalizedDifference(['B8',  'B4' ]).rename('NDVI')
mndwi = image_ee.normalizedDifference(['B3',  'B11']).rename('MNDWI')
ndbi  = image_ee.normalizedDifference(['B11', 'B8' ]).rename('NDBI')

# Máscara de água espectral
water_mask = mndwi.gt(0.05).And(ndvi.lt(0.1))

# Stack: 5 bandas + 3 índices = 8 canais
image_stack = image_ee.select(['B2', 'B3', 'B4', 'B8', 'B11']).addBands([
    ndvi.multiply(2),
    mndwi.multiply(3),
    ndbi.multiply(2)
])

image_stack = image_stack.clip(region)
image_stack = image_stack.updateMask(image_stack.mask().reduce(ee.Reducer.min()))

# Converter para NumPy
image = geemap.ee_to_numpy(image_stack, region=region, scale=10)
water_np = geemap.ee_to_numpy(water_mask, region=region, scale=10).astype(bool)

print(f'Shape do stack: {image.shape}')  # (H, W, 8)
print(f'Shape da máscara de água: {water_np.shape}')

"""# **Pré-processamento da Imagem Multiespectral**

Normalização por banda (percentis 2-98) e suavização Gaussiana.

"""

if image is None or np.count_nonzero(image) == 0:
    raise ValueError("Imagem vazia ou inválida")

image = image.astype(np.float32)

for b in range(image.shape[2]):
    band = image[:, :, b]
    p2  = np.nanpercentile(band, 2)
    p98 = np.nanpercentile(band, 98)
    den = p98 - p2
    if den > 1e-8:
        band = np.clip((band - p2) / den, 0, 1)
    else:
        band = np.zeros_like(band)
    image[:, :, b] = band

image_blur = cv2.GaussianBlur(image, (5, 5), 0)

# RGB para visualização
rgb_vis = np.clip(image_blur[:, :, :3] ** 0.8, 0, 1)
rgb_vis_uint8 = (rgb_vis * 255).astype(np.uint8)

print(f'Imagem pré-processada: {image_blur.shape}')

"""# **Geração do Pseudo Ground Truth com K-Means**

Como não temos máscaras anotadas manualmente, usamos o K-Means para gerar
rótulos iniciais (pseudo ground truth). Isso é uma abordagem comum em
aprendizado semi-supervisionado para sensoriamento remoto.

**Por que isso funciona?**
- O K-Means captura agrupamentos espectrais razoáveis
- A U-Net vai aprender a generalizar esses padrões espacialmente,
  beneficiando-se de sua arquitetura convolucional para capturar
  contexto espacial que o K-Means ignora completamente

**Classes:** 0=Água, 1=Areia, 2=Vegetação, 3=Urbanização

"""

# --- Preparação dos pixels para K-Means ---
pixels = image_blur.reshape((-1, image_blur.shape[2]))
water_flat = water_np.flatten()
pixel_sum = np.sum(np.abs(pixels), axis=1)
valid_pixels = (pixel_sum > 0) & (~water_flat)
pixels_valid = pixels[valid_pixels]

scaler = StandardScaler()
pixels_scaled = scaler.fit_transform(pixels_valid)

# --- K-Means com 4 clusters terrestres ---
print("Rodando K-Means para gerar pseudo ground truth...")
kmeans = KMeans(n_clusters=4, random_state=100, n_init=50)
kmeans.fit(pixels_scaled)
labels_valid = kmeans.labels_

# --- Reconstrução do mapa de classes ---
labels_full = np.full(pixels.shape[0], -1)
labels_full[water_flat]   = 0         # água = classe 0
labels_full[valid_pixels] = labels_valid + 1  # clusters terrestres: 1, 2, 3, 4
class_map = labels_full.reshape(image_blur.shape[:2])

# --- Visualização dos clusters para interpretação manual ---
fig, axes = plt.subplots(2, 3, figsize=(18, 10))
axes = axes.ravel()

for i in range(5):
    cluster_mask = (class_map == i)
    overlay = np.zeros((*class_map.shape, 4), dtype=np.float32)
    overlay[..., 3] = (~cluster_mask) * 0.85
    axes[i].imshow(rgb_vis_uint8)
    axes[i].imshow(overlay)
    axes[i].set_title('Água (fixa)' if i == 0 else f'Cluster {i}')
    axes[i].axis('off')

axes[5].axis('off')
plt.suptitle('Clusters K-Means — Interpretar para definir classes temáticas', fontsize=13)
plt.tight_layout()
plt.show()

# =====================================================
# >>> ATENÇÃO: AJUSTE AQUI CONFORME SUA INTERPRETAÇÃO
# =====================================================

#   Após visualizar os clusters acima, defina quais
#   clusters K-Means correspondem a cada classe temática.
#   Os valores são os rótulos do class_map (1, 2, 3 ou 4).

agua        = [0]     # ÁGUA — sempre 0 (máscara espectral)
areia       = [4]     # AJUSTE conforme visualização ###########
vegetacao   = [2]     # AJUSTE conforme visualização ###########
urbanizacao = [1, 3]  # AJUSTE conforme visualização ###########

# =====================================================

# --- Construção do pseudo ground truth temático ---
pseudo_gt = np.full_like(class_map, -1)

for c in agua:
    pseudo_gt[class_map == c] = 0
for c in areia:
    pseudo_gt[class_map == c] = 1
for c in vegetacao:
    pseudo_gt[class_map == c] = 2
for c in urbanizacao:
    pseudo_gt[class_map == c] = 3

# Suavização para reduzir ruído nos rótulos
pseudo_gt_valid = pseudo_gt.copy()
pseudo_gt_valid[pseudo_gt_valid == -1] = 0
pseudo_gt = median_filter(pseudo_gt_valid, size=3)

# --- Visualização do pseudo GT ---
colors_gt = ['blue', 'khaki', 'green', 'gray']
cmap_gt   = ListedColormap(colors_gt)

plt.figure(figsize=(10, 10))
plt.imshow(pseudo_gt, cmap=cmap_gt, vmin=0, vmax=3)
plt.title('Pseudo Ground Truth (K-Means → classes temáticas)')
plt.axis('off')
legend_patches = [
    mpatches.Patch(color=colors_gt[i], label=n)
    for i, n in enumerate(['Água', 'Areia', 'Vegetação', 'Urbanização'])
]
plt.legend(handles=legend_patches, loc='upper right', fontsize=10)
plt.tight_layout()
plt.show()

print(f"Pseudo GT shape: {pseudo_gt.shape}")
print(f"Classes únicas: {np.unique(pseudo_gt)}")

"""# **Dataset de Patches para Treinamento**

A U-Net trabalha com patches (recortes) da imagem para:
- Aumentar a quantidade de amostras de treinamento
- Permitir data augmentation
- Gerenciar o uso de memória da GPU

**Parâmetros:**
- PATCH_SIZE: tamanho do patch em pixels (ex: 64×64)
- STRIDE: deslocamento entre patches (< PATCH_SIZE = sobreposição)

"""

# =====================================================
# >>> PARÂMETROS DO DATASET — AJUSTE SE NECESSÁRIO
PATCH_SIZE  = 64    # tamanho do patch (64 ou 128)
STRIDE      = 32    # stride (sobreposição de 50% com stride=32)
BATCH_SIZE  = 16    # amostras por batch
VAL_SPLIT   = 0.2   # 20% dos patches para validação
# =====================================================

class SentinelPatchDataset(Dataset):
    """
    Dataset que extrai patches da imagem multiespectral e da máscara.

    Args:
        image  : np.ndarray (H, W, C) — imagem normalizada
        mask   : np.ndarray (H, W)    — mapa de classes
        patch_size : int
        stride     : int
        augment    : bool — aplica flip aleatório se True
    """

    def __init__(self, image, mask, patch_size=64, stride=32, augment=False):
        self.image      = image
        self.mask       = mask
        self.patch_size = patch_size
        self.augment    = augment
        self.patches    = []

        H, W = mask.shape
        ps   = patch_size

        # Extrai coordenadas de todos os patches válidos
        for y in range(0, H - ps + 1, stride):
            for x in range(0, W - ps + 1, stride):
                img_patch  = image[y:y+ps, x:x+ps, :]
                mask_patch = mask[y:y+ps, x:x+ps]

                # Ignora patches predominantemente inválidos
                valid_ratio = np.mean(mask_patch >= 0)
                if valid_ratio < 0.5:
                    continue

                self.patches.append((img_patch.copy(), mask_patch.copy()))

        print(f"Total de patches extraídos: {len(self.patches)}")

    def __len__(self):
        return len(self.patches)

    def __getitem__(self, idx):
        img, msk = self.patches[idx]

        # Augmentação: flip horizontal e vertical aleatórios
        if self.augment:
            if np.random.rand() > 0.5:
                img = np.flip(img, axis=1).copy()
                msk = np.flip(msk, axis=1).copy()
            if np.random.rand() > 0.5:
                img = np.flip(img, axis=0).copy()
                msk = np.flip(msk, axis=0).copy()

        # (H, W, C) → (C, H, W) para PyTorch
        img_tensor = torch.from_numpy(img.transpose(2, 0, 1)).float()

        # Máscara: substitui -1 por 0 (pixels inválidos viram classe 0)
        msk = msk.copy()
        msk[msk < 0] = 0
        msk_tensor = torch.from_numpy(msk).long()

        return img_tensor, msk_tensor


# Criar dataset completo
full_dataset = SentinelPatchDataset(
    image_blur,
    pseudo_gt,
    patch_size=PATCH_SIZE,
    stride=STRIDE,
    augment=False
)

# Divisão treino / validação
n_val   = int(len(full_dataset) * VAL_SPLIT)
n_train = len(full_dataset) - n_val

train_dataset, val_dataset = random_split(
    full_dataset,
    [n_train, n_val],
    generator=torch.Generator().manual_seed(42)
)

# Ativar augmentation apenas no treino
train_dataset.dataset.augment = True

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True,  num_workers=2, pin_memory=True)
val_loader   = DataLoader(val_dataset,   batch_size=BATCH_SIZE, shuffle=False, num_workers=2, pin_memory=True)

print(f"\nPatches de treino    : {n_train}")
print(f"Patches de validação : {n_val}")
print(f"Batches por época    : {len(train_loader)}")

"""# **Visualização da segmentação em patches**

"""

# ==========================================
# Escolhe um patch próximo ao centro
# (3 patches para a direita)
# ==========================================
H, W = image_blur.shape[:2]

# Patch central
x0 = (W // 2 // STRIDE) * STRIDE
y0 = (H // 2 // STRIDE) * STRIDE

# Move 3 patches para a direita
x0 += -4 * STRIDE

# Garante que não saia da imagem
x0 = min(x0, W - PATCH_SIZE)

# Extrai o patch
patch = image_blur[y0:y0+PATCH_SIZE, x0:x0+PATCH_SIZE, :3]

# Normalização para visualização
rgb = image_blur[:, :, :3].astype(float)
rgb = (rgb - rgb.min()) / (rgb.max() - rgb.min())

patch = patch.astype(float)
patch = (patch - patch.min()) / (patch.max() - patch.min())

# ==========================================
# Figura
# ==========================================
fig = plt.figure(figsize=(16,6))

# -----------------------------
# Painel 1 - Imagem original
# -----------------------------
ax1 = plt.subplot(1,3,1)

ax1.imshow(rgb)
ax1.set_title("Imagem Sentinel-2")
ax1.axis("off")

# Destaca o patch escolhido
ax1.add_patch(
    Rectangle(
        (x0, y0),
        PATCH_SIZE,
        PATCH_SIZE,
        edgecolor="yellow",
        linewidth=2.5,
        facecolor="none"
    )
)

# -----------------------------
# Painel 2 - Grade de patches
# -----------------------------
ax2 = plt.subplot(1,3,2)

ax2.imshow(rgb)

for y in range(0, H - PATCH_SIZE + 1, STRIDE):
    for x in range(0, W - PATCH_SIZE + 1, STRIDE):

        mask_patch = pseudo_gt[y:y+PATCH_SIZE, x:x+PATCH_SIZE]

        if np.mean(mask_patch >= 0) < 0.5:
            continue

        ax2.add_patch(
            Rectangle(
                (x, y),
                PATCH_SIZE,
                PATCH_SIZE,
                edgecolor="red",
                linewidth=0.25,
                facecolor="none"
            )
        )

# Destaca novamente o patch escolhido
ax2.add_patch(
    Rectangle(
        (x0, y0),
        PATCH_SIZE,
        PATCH_SIZE,
        edgecolor="yellow",
        linewidth=2.5,
        facecolor="none"
    )
)

ax2.set_title(f"Divisão em patches\n{PATCH_SIZE}×{PATCH_SIZE} pixels | stride = {STRIDE}")
ax2.axis("off")

# -----------------------------
# Painel 3 - Patch ampliado
# -----------------------------
ax3 = plt.subplot(1,3,3)

ax3.imshow(patch)
ax3.set_title(f"Patch selecionado\n{PATCH_SIZE}×{PATCH_SIZE} pixels")
ax3.axis("off")

plt.tight_layout()
plt.show()

"""# **Arquitetura U-Net**

A U-Net é uma rede encoder-decoder com skip connections.
Foi originalmente proposta para segmentação biomédica e é o
estado da arte para segmentação de imagens de satélite.

**Estrutura:**
- Encoder (contração): extrai features progressivamente
- Bottleneck: representação mais comprimida
- Decoder (expansão): reconstrói a resolução espacial
- Skip connections: concatenam features do encoder no decoder,
  preservando detalhes espaciais

**Entrada:** tensor (B, 8, H, W) — 8 canais espectrais
**Saída:**   tensor (B, 4, H, W) — logits para 4 classes

"""

class ConvBlock(nn.Module):
    """Bloco básico: Conv → BN → ReLU → Conv → BN → ReLU"""
    def __init__(self, in_ch, out_ch):
        super().__init__()
        self.block = nn.Sequential(
            nn.Conv2d(in_ch, out_ch, kernel_size=3, padding=1, bias=False),
            nn.BatchNorm2d(out_ch),
            nn.ReLU(inplace=True),
            nn.Conv2d(out_ch, out_ch, kernel_size=3, padding=1, bias=False),
            nn.BatchNorm2d(out_ch),
            nn.ReLU(inplace=True),
        )

    def forward(self, x):
        return self.block(x)


class EncoderBlock(nn.Module):
    """Bloco encoder: ConvBlock + MaxPool"""
    def __init__(self, in_ch, out_ch):
        super().__init__()
        self.conv = ConvBlock(in_ch, out_ch)
        self.pool = nn.MaxPool2d(2)

    def forward(self, x):
        skip = self.conv(x)   # guarda para o skip connection
        x    = self.pool(skip)
        return x, skip


class DecoderBlock(nn.Module):
    """Bloco decoder: Upsample + concatenação + ConvBlock"""
    def __init__(self, in_ch, skip_ch, out_ch):
        super().__init__()
        self.up   = nn.ConvTranspose2d(in_ch, out_ch, kernel_size=2, stride=2)
        self.conv = ConvBlock(out_ch + skip_ch, out_ch)

    def forward(self, x, skip):
        x = self.up(x)
        x = torch.cat([x, skip], dim=1)   # skip connection
        return self.conv(x)


class UNet(nn.Module):
    """
    U-Net para segmentação semântica multiespectral.

    Args:
        in_channels  : número de bandas de entrada (8)
        num_classes  : número de classes de saída (4)
        base_filters : número de filtros no primeiro bloco (32 ou 64)
    """
    def __init__(self, in_channels=8, num_classes=4, base_filters=32):
        super().__init__()
        f = base_filters

        # Encoder
        self.enc1 = EncoderBlock(in_channels, f)      # 8 → 32
        self.enc2 = EncoderBlock(f,           f*2)    # 32 → 64
        self.enc3 = EncoderBlock(f*2,         f*4)    # 64 → 128
        self.enc4 = EncoderBlock(f*4,         f*8)    # 128 → 256

        # Bottleneck
        self.bottleneck = ConvBlock(f*8, f*16)        # 256 → 512

        # Decoder
        self.dec4 = DecoderBlock(f*16, f*8,  f*8)    # 512, 256 → 256
        self.dec3 = DecoderBlock(f*8,  f*4,  f*4)    # 256, 128 → 128
        self.dec2 = DecoderBlock(f*4,  f*2,  f*2)    # 128, 64  → 64
        self.dec1 = DecoderBlock(f*2,  f,    f)       # 64, 32   → 32

        # Classificador final
        self.head = nn.Conv2d(f, num_classes, kernel_size=1)

    def forward(self, x):
        # Encoder
        x, s1 = self.enc1(x)
        x, s2 = self.enc2(x)
        x, s3 = self.enc3(x)
        x, s4 = self.enc4(x)

        # Bottleneck
        x = self.bottleneck(x)

        # Decoder com skip connections
        x = self.dec4(x, s4)
        x = self.dec3(x, s3)
        x = self.dec2(x, s2)
        x = self.dec1(x, s1)

        return self.head(x)


# Instanciar modelo
model = UNet(in_channels=8, num_classes=4, base_filters=32).to(DEVICE)

# Contar parâmetros
total_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"Parâmetros treináveis: {total_params:,}")

# Teste rápido do forward pass
dummy = torch.randn(2, 8, PATCH_SIZE, PATCH_SIZE).to(DEVICE)
out   = model(dummy)
print(f"Input shape : {dummy.shape}")
print(f"Output shape: {out.shape}")   # deve ser (2, 4, 64, 64)

"""# **Loss, Otimizador e Scheduler**

Usamos uma combinação de duas funções de loss:

**CrossEntropyLoss:** penaliza erros de classificação por pixel.

**Dice Loss:** otimiza diretamente o coeficiente Dice (métrica de
sobreposição), especialmente útil quando as classes são desbalanceadas
(ex: área de água muito menor que área urbana).

A combinação das duas (CE + Dice) costuma dar melhores resultados
do que qualquer uma isoladamente.

"""

class DiceLoss(nn.Module):
    """Dice Loss para segmentação semântica multiclasse."""
    def __init__(self, num_classes=4, smooth=1.0):
        super().__init__()
        self.num_classes = num_classes
        self.smooth      = smooth

    def forward(self, logits, targets):
        probs = torch.softmax(logits, dim=1)   # (B, C, H, W)
        loss  = 0.0

        for c in range(self.num_classes):
            pred_c   = probs[:, c, :, :]
            target_c = (targets == c).float()

            intersection = (pred_c * target_c).sum()
            union        = pred_c.sum() + target_c.sum()

            dice = (2. * intersection + self.smooth) / (union + self.smooth)
            loss += 1 - dice

        return loss / self.num_classes


class CombinedLoss(nn.Module):
    """CrossEntropy + Dice Loss com peso ajustável."""
    def __init__(self, num_classes=4, ce_weight=0.5, dice_weight=0.5):
        super().__init__()
        self.ce        = nn.CrossEntropyLoss()
        self.dice      = DiceLoss(num_classes)
        self.ce_w      = ce_weight
        self.dice_w    = dice_weight

    def forward(self, logits, targets):
        return self.ce_w * self.ce(logits, targets) + \
               self.dice_w * self.dice(logits, targets)


# =====================================================
# >>> HIPERPARÂMETROS — AJUSTE SE NECESSÁRIO
NUM_EPOCHS    = 50       # número de épocas de treinamento
LEARNING_RATE = 1e-3     # taxa de aprendizado inicial
WEIGHT_DECAY  = 1e-4     # regularização L2
# =====================================================

criterion = CombinedLoss(num_classes=4, ce_weight=0.5, dice_weight=0.5).to(DEVICE)
optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE, weight_decay=WEIGHT_DECAY)

# Scheduler: reduz LR quando a loss de validação para de melhorar
scheduler = optim.lr_scheduler.ReduceLROnPlateau(
    optimizer, mode='min', factor=0.5, patience=5
)

print("Loss, otimizador e scheduler configurados.")

"""# **Treinamento da U-Net**

Loop de treinamento com:
- Monitoramento de loss e acurácia por época
- Early stopping automático (para quando a validação piora)
- Checkpoint do melhor modelo

"""

def compute_accuracy(logits, targets):
    """Acurácia pixel a pixel."""
    preds = logits.argmax(dim=1)
    return (preds == targets).float().mean().item()


def train_one_epoch(model, loader, criterion, optimizer, device):
    model.train()
    total_loss, total_acc = 0.0, 0.0

    for imgs, masks in loader:
        imgs, masks = imgs.to(device), masks.to(device)

        optimizer.zero_grad()
        logits = model(imgs)
        loss   = criterion(logits, masks)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()
        total_acc  += compute_accuracy(logits, masks)

    return total_loss / len(loader), total_acc / len(loader)


def validate(model, loader, criterion, device):
    model.eval()
    total_loss, total_acc = 0.0, 0.0

    with torch.no_grad():
        for imgs, masks in loader:
            imgs, masks = imgs.to(device), masks.to(device)
            logits = model(imgs)
            loss   = criterion(logits, masks)
            total_loss += loss.item()
            total_acc  += compute_accuracy(logits, masks)

    return total_loss / len(loader), total_acc / len(loader)


# --- Histórico ---
history = {'train_loss': [], 'val_loss': [], 'train_acc': [], 'val_acc': []}

best_val_loss   = float('inf')
patience_count  = 0
EARLY_STOP_PAT  = 10  # épocas sem melhora antes de parar

print("=" * 55)
print("INICIANDO TREINAMENTO DA U-NET")
print("=" * 55)

for epoch in range(1, NUM_EPOCHS + 1):

    train_loss, train_acc = train_one_epoch(model, train_loader, criterion, optimizer, DEVICE)
    val_loss,   val_acc   = validate(model, val_loader, criterion, DEVICE)

    scheduler.step(val_loss)

    history['train_loss'].append(train_loss)
    history['val_loss'].append(val_loss)
    history['train_acc'].append(train_acc)
    history['val_acc'].append(val_acc)

    print(f"Época {epoch:3d}/{NUM_EPOCHS} | "
          f"Loss Treino: {train_loss:.4f} | Loss Val: {val_loss:.4f} | "
          f"Acc Treino: {train_acc*100:.1f}% | Acc Val: {val_acc*100:.1f}%")

    # Salva melhor modelo
    if val_loss < best_val_loss:
        best_val_loss = val_loss
        patience_count = 0
        torch.save(model.state_dict(), 'best_unet.pth')
        print(f"  → Melhor modelo salvo! (val_loss={best_val_loss:.4f})")
    else:
        patience_count += 1
        if patience_count >= EARLY_STOP_PAT:
            print(f"\nEarly stopping na época {epoch} (sem melhora por {EARLY_STOP_PAT} épocas)")
            break

print("\nTreinamento concluído!")

"""# **Curvas de Aprendizado**

Visualização do progresso do treinamento ao longo das épocas.
As curvas devem convergir — treino e validação próximos indicam
boa generalização do modelo.

"""

epochs_range = range(1, len(history['train_loss']) + 1)

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].plot(epochs_range, history['train_loss'], label='Treino', linewidth=2)
axes[0].plot(epochs_range, history['val_loss'],   label='Validação', linewidth=2)
axes[0].set_xlabel('Época')
axes[0].set_ylabel('Loss (CE + Dice)')
axes[0].set_title('Curva de Loss')
axes[0].legend()
axes[0].grid(True, alpha=0.3)

axes[1].plot(epochs_range, [a*100 for a in history['train_acc']], label='Treino', linewidth=2)
axes[1].plot(epochs_range, [a*100 for a in history['val_acc']],   label='Validação', linewidth=2)
axes[1].set_xlabel('Época')
axes[1].set_ylabel('Acurácia (%)')
axes[1].set_title('Curva de Acurácia')
axes[1].legend()
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

"""# **Inferência — Segmentação da Imagem Completa**

Carregamos o melhor modelo salvo e realizamos a inferência
por sliding window (janela deslizante) na imagem inteira.

A soma dos logits com sobreposição seguida de argmax garante
bordas suaves entre os patches.

"""

# Carregar melhor modelo
model.load_state_dict(torch.load('best_unet.pth', map_location=DEVICE))
model.eval()
print("Melhor modelo carregado.")

H, W, C = image_blur.shape
ps      = PATCH_SIZE

# Acumuladores para inferência com sobreposição
logits_accum = np.zeros((4, H, W), dtype=np.float32)
count_accum  = np.zeros((H, W),    dtype=np.float32)

INFER_STRIDE = ps // 2   # 50% de sobreposição para suavizar bordas

with torch.no_grad():
    for y in range(0, H - ps + 1, INFER_STRIDE):
        for x in range(0, W - ps + 1, INFER_STRIDE):
            patch = image_blur[y:y+ps, x:x+ps, :]
            patch_tensor = torch.from_numpy(
                patch.transpose(2, 0, 1)
            ).unsqueeze(0).float().to(DEVICE)

            logits = model(patch_tensor).squeeze(0).cpu().numpy()  # (4, ps, ps)

            logits_accum[:, y:y+ps, x:x+ps] += logits
            count_accum[y:y+ps, x:x+ps]     += 1

    # Colunas e linhas da borda direita/inferior (que podem não ter sido cobertas)
    # Última coluna
    if W - ps > 0:
        for y in range(0, H - ps + 1, INFER_STRIDE):
            patch = image_blur[y:y+ps, W-ps:W, :]
            patch_tensor = torch.from_numpy(patch.transpose(2, 0, 1)).unsqueeze(0).float().to(DEVICE)
            logits = model(patch_tensor).squeeze(0).cpu().numpy()
            logits_accum[:, y:y+ps, W-ps:W] += logits
            count_accum[y:y+ps, W-ps:W]     += 1

    # Última linha
    if H - ps > 0:
        for x in range(0, W - ps + 1, INFER_STRIDE):
            patch = image_blur[H-ps:H, x:x+ps, :]
            patch_tensor = torch.from_numpy(patch.transpose(2, 0, 1)).unsqueeze(0).float().to(DEVICE)
            logits = model(patch_tensor).squeeze(0).cpu().numpy()
            logits_accum[:, H-ps:H, x:x+ps] += logits
            count_accum[H-ps:H, x:x+ps]     += 1

# Média dos logits acumulados
count_accum[count_accum == 0] = 1  # evita divisão por zero
logits_accum /= count_accum

# Mapa de predição final
pred_map = np.argmax(logits_accum, axis=0)  # (H, W) com valores 0-3

print(f"Mapa de predição gerado: {pred_map.shape}")
print(f"Classes preditas: {np.unique(pred_map)}")

"""# **Pós-processamento — Remoção de Pixels Isolados**

Após a inferência, ainda existem pequenos agrupamentos de areia
dentro de regiões de urbanização (e vice-versa). Isso ocorre porque
o pseudo ground truth gerado pelo K-Means já continha essa confusão,
e a U-Net a aprendeu parcialmente.

Este bloco usa análise de componentes conectados para identificar
"ilhas" pequenas de areia dentro de urbanização e convertê-las para
a classe dominante na vizinhança.

**Parâmetro MIN_AREA:** tamanho mínimo em pixels para manter um
componente de areia. Componentes menores que isso dentro de
urbanização são removidos. Aumente se ainda sobrar pontinhos,
diminua se começar a apagar praias reais.

"""

from scipy.ndimage import label, binary_erosion, binary_dilation

pred_map_clean = pred_map.copy()

# Mantém só areia que toca a água (dentro de X pixels)
agua_mask = (pred_map_clean == 0)
agua_dilatada = binary_dilation(agua_mask, iterations=20)  # 150m da água

# Areia fora dessa faixa vira urbanização
areia_fora = (pred_map_clean == 1) & ~agua_dilatada
pred_map_clean[areia_fora] = 3

print(f"Pixels de areia antes : {np.sum(pred_map == 1)}")
print(f"Pixels de areia depois: {np.sum(pred_map_clean == 1)}")
print(f"Pixels corrigidos     : {np.sum(areia_fora)}")

"""# **Mapa Temático Final — U-Net**

Visualização do mapa de segmentação semântica gerado pela U-Net
com cálculo de área por classe.

"""

from matplotlib.colors import ListedColormap
from matplotlib.patches import Patch
import matplotlib.pyplot as plt
import numpy as np

pixel_area = 100  # m² por pixel (10 × 10 m)

# ==============================
# Colormaps
# ==============================

colors_map = ['blue', 'khaki', 'green', 'gray']
cmap_map = ListedColormap(colors_map)

# Água = azul | Faixa dilatada = vermelho
mask_vis = np.zeros((*agua_dilatada.shape, 3))

# fundo branco
mask_vis[:] = [1, 1, 1]

# faixa dilatada
mask_vis[agua_dilatada] = [1.0, 0.25, 0.25]

# água original
mask_vis[agua_mask] = [0.0, 0.3, 1.0]

# ==============================
# Figura
# ==============================

fig, ax = plt.subplots(1, 3, figsize=(18, 6))

# ----------------------------------
# Painel 1
# ----------------------------------

ax[0].imshow(pred_map, cmap=cmap_map, vmin=0, vmax=3)
ax[0].set_title("a) Classificação inicial", fontsize=12)
ax[0].axis("off")

# ----------------------------------
# Painel 2
# ----------------------------------

ax[1].imshow(mask_vis)
ax[1].set_title("b) Dilatação da água (150 m)", fontsize=12)
ax[1].axis("off")

legend_mask = [
    Patch(facecolor=(0.0,0.3,1.0), label="Água"),
    Patch(facecolor=(1.0,0.25,0.25), label="Faixa de 150 m")
]

ax[1].legend(
    handles=legend_mask,
    loc="lower center",
    bbox_to_anchor=(0.5,-0.12),
    ncol=2,
    frameon=True,
    fontsize=9
)

# ----------------------------------
# Painel 3
# ----------------------------------

ax[2].imshow(pred_map_clean, cmap=cmap_map, vmin=0, vmax=3)
ax[2].set_title("c) Classificação após o pós-processamento", fontsize=12)
ax[2].axis("off")

# ==============================
# Legenda principal
# ==============================

area_agua        = np.sum(pred_map == 0) * pixel_area
area_areia       = np.sum(pred_map == 1) * pixel_area
area_vegetacao   = np.sum(pred_map == 2) * pixel_area
area_urbanizacao = np.sum(pred_map == 3) * pixel_area

legend_classes = [
    Patch(facecolor='blue',  label=f'Água ({area_agua:,.0f} m²)'),
    Patch(facecolor='khaki', label=f'Areia ({area_areia:,.0f} m²)'),
    Patch(facecolor='green', label=f'Vegetação ({area_vegetacao:,.0f} m²)'),
    Patch(facecolor='gray',  label=f'Urbanização ({area_urbanizacao:,.0f} m²)')
]

fig.legend(
    handles=legend_classes,
    loc="lower center",
    bbox_to_anchor=(0.5,-0.03),
    ncol=4,
    frameon=True,
    fontsize=10
)

plt.tight_layout(rect=[0,0.08,1,1])

plt.show()

"""# **Comparação Visual: U-Net × Pseudo GT (K-Means)**

"""

fig, axes = plt.subplots(1, 3, figsize=(22, 8))

axes[0].imshow(rgb_vis_uint8)
axes[0].set_title('RGB Original', fontsize=13)
axes[0].axis('off')

axes[1].imshow(pseudo_gt, cmap=cmap_map, vmin=0, vmax=3)
axes[1].set_title('Pseudo GT — K-Means', fontsize=13)
axes[1].axis('off')

axes[2].imshow(pred_map, cmap=cmap_map, vmin=0, vmax=3)
axes[2].set_title('U-Net (IA Generativa)', fontsize=13)
axes[2].axis('off')

# Legenda compartilhada
legend_patches = [
    mpatches.Patch(color=colors_map[i], label=n)
    for i, n in enumerate(['Água', 'Areia', 'Vegetação', 'Urbanização'])
]
fig.legend(
    handles=legend_patches,
    loc='lower center',
    ncol=4,
    fontsize=11,
    frameon=True,
    bbox_to_anchor=(0.5, -0.02)
)

plt.suptitle('Comparação: Visão Clássica × U-Net', fontsize=15, y=1.02)
plt.tight_layout()
plt.show()

"""# **Métricas de Avaliação: IoU e Dice**

**IoU (Intersection over Union):** mede a sobreposição entre a
predição e o ground truth para cada classe. É a métrica padrão
para segmentação semântica.

**Dice Score:** similar ao IoU, mas pondera mais a sobreposição.
É equivalente ao F1-Score na segmentação.

Avaliamos a U-Net contra o pseudo ground truth. Uma acurácia
superior à do K-Means indica que a U-Net generalizou melhor
os padrões espaciais.

"""

NUM_CLASSES  = 4
CLASS_NAMES  = ['Água', 'Areia', 'Vegetação', 'Urbanização']

def compute_iou_dice(pred, gt, num_classes):
    """Calcula IoU e Dice por classe."""
    iou_list, dice_list = [], []

    for c in range(num_classes):
        pred_c = (pred == c)
        gt_c   = (gt   == c)

        intersection = np.logical_and(pred_c, gt_c).sum()
        union        = np.logical_or(pred_c,  gt_c).sum()
        sum_both     = pred_c.sum() + gt_c.sum()

        iou  = intersection / (union + 1e-8)
        dice = (2 * intersection) / (sum_both + 1e-8)

        iou_list.append(iou)
        dice_list.append(dice)

    return np.array(iou_list), np.array(dice_list)


iou_scores, dice_scores = compute_iou_dice(pred_map, pseudo_gt, NUM_CLASSES)
mean_iou  = np.mean(iou_scores)
mean_dice = np.mean(dice_scores)

print("=" * 50)
print("MÉTRICAS — U-Net vs Pseudo Ground Truth")
print("=" * 50)
print(f"{'Classe':<15} {'IoU':>8} {'Dice':>8}")
print("-" * 35)
for i, name in enumerate(CLASS_NAMES):
    print(f"{name:<15} {iou_scores[i]:>8.4f} {dice_scores[i]:>8.4f}")
print("-" * 35)
print(f"{'Mean (mIoU)':<15} {mean_iou:>8.4f} {mean_dice:>8.4f}")
print("=" * 50)

# --- Gráfico de barras ---
x = np.arange(NUM_CLASSES)
width = 0.35

fig, ax = plt.subplots(figsize=(10, 5))
bars1 = ax.bar(x - width/2, iou_scores,  width, label='IoU',  color='steelblue',  alpha=0.85)
bars2 = ax.bar(x + width/2, dice_scores, width, label='Dice', color='darkorange', alpha=0.85)

ax.set_ylabel('Score')
ax.set_title('IoU e Dice por Classe — U-Net')
ax.set_xticks(x)
ax.set_xticklabels(CLASS_NAMES)
ax.set_ylim(0, 1.05)
ax.axhline(mean_iou,  color='steelblue',  linestyle='--', linewidth=1.2, label=f'mIoU={mean_iou:.3f}')
ax.axhline(mean_dice, color='darkorange', linestyle='--', linewidth=1.2, label=f'mDice={mean_dice:.3f}')
ax.legend()
ax.grid(axis='y', alpha=0.3)

for bar in bars1:
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
            f'{bar.get_height():.3f}', ha='center', va='bottom', fontsize=9)
for bar in bars2:
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
            f'{bar.get_height():.3f}', ha='center', va='bottom', fontsize=9)

plt.tight_layout()
plt.show()

"""# **Acurácia Global e Matriz de Confusão — U-Net vs Pseudo GT**

A matriz de confusão mostra, por classe, quantos pixels foram
corretamente ou incorretamente segmentados. A diagonal principal
representa os acertos.

Comparamos também com a acurácia do K-Means (pseudo GT contra si mesmo
seria 100%, então comparamos U-Net vs pseudo GT com K-Means vs pseudo GT
em sub-regiões de validação).

"""

# --- Acurácia global ---
unet_flat = pred_map.flatten()
gt_flat   = pseudo_gt.flatten()

valid_mask = (gt_flat >= 0)
unet_valid = unet_flat[valid_mask]
gt_valid   = gt_flat[valid_mask]

global_acc = accuracy_score(gt_valid, unet_valid)
print(f"\nACURÁCIA GLOBAL — U-Net vs Pseudo GT: {global_acc*100:.2f}%")

# --- Matriz de confusão ---
cm      = confusion_matrix(gt_valid, unet_valid)
cm_m2   = cm * pixel_area
cm_norm = cm / cm.sum(axis=1, keepdims=True)
cm_norm = np.nan_to_num(cm_norm)

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

ConfusionMatrixDisplay(cm_m2, display_labels=CLASS_NAMES).plot(
    cmap='Blues', ax=axes[0], colorbar=True
)
axes[0].set_title('U-Net vs Pseudo GT (m²)')
axes[0].set_xlabel('U-Net')
axes[0].set_ylabel('Pseudo GT')

ConfusionMatrixDisplay(cm_norm, display_labels=CLASS_NAMES).plot(
    cmap='Greens', ax=axes[1], colorbar=True, values_format='.2f'
)
axes[1].set_title('U-Net vs Pseudo GT (Normalizado)')
axes[1].set_xlabel('U-Net')
axes[1].set_ylabel('Pseudo GT')

plt.tight_layout()
plt.show()

"""# **Mapa Espacial de Divergências**

Pixels em vermelho indicam onde a U-Net discorda do pseudo GT.
Regiões de divergência são esperadas e desejáveis em bordas e
áreas espectralmente ambíguas — a U-Net pode capturar melhor
a continuidade espacial nesses pontos.

"""

error_map = np.full(pred_map.shape, -1)

valid2d = (pseudo_gt >= 0)
error_map[valid2d] = (pred_map[valid2d] != pseudo_gt[valid2d]).astype(np.uint8)

cmap_err = ListedColormap(['none', 'red'])

plt.figure(figsize=(10, 10))
plt.imshow(rgb_vis_uint8)
plt.imshow(error_map, cmap=cmap_err, vmin=0, vmax=1, alpha=0.6)
plt.title('Divergências: U-Net × Pseudo GT\n(vermelho = discordância)', fontsize=13)
plt.axis('off')

error_rate = error_map[error_map >= 0].mean() * 100
plt.text(
    10, 20,
    f'Taxa de erro: {error_rate:.1f}%',
    color='white',
    fontsize=12,
    bbox=dict(facecolor='black', alpha=0.6)
)

plt.tight_layout()
plt.show()

"""# **Resumo Final dos Resultados**

"""

print("\n" + "=" * 60)
print("RESUMO — SEGMENTAÇÃO U-NET (IA GENERATIVA)")
print("=" * 60)
print(f"\nModelo: U-Net (PyTorch)")
print(f"Entrada: {C} canais espectrais (B2, B3, B4, B8, B11, NDVI, MNDWI, NDBI)")
print(f"Resolução: 10m/pixel")
print(f"Patches de treino: {n_train}  |  Validação: {n_val}")
print(f"Épocas treinadas: {len(history['train_loss'])}")
print(f"\nMétricas (U-Net vs Pseudo GT):")
print(f"  Acurácia Global : {global_acc*100:.2f}%")
print(f"  mIoU            : {mean_iou:.4f}")
print(f"  mDice           : {mean_dice:.4f}")
print(f"\nIoU por classe:")
for i, name in enumerate(CLASS_NAMES):
    print(f"  {name:<15}: {iou_scores[i]:.4f}")
print(f"\nÁreas estimadas pela U-Net:")
print(f"  Água        : {area_agua:>12,.0f} m²")
print(f"  Areia       : {area_areia:>12,.0f} m²")
print(f"  Vegetação   : {area_vegetacao:>12,.0f} m²")
print(f"  Urbanização : {area_urbanizacao:>12,.0f} m²")
print("=" * 60)